

 const Fonts_list = [
  "Abel-Regular.ttf",
  "Academic M54.ttf",
  "Acids!.otf",
  "Aileron-BlackItalic.otf",
  "Aileron-Black.otf",
  "Aileron-BoldItalic.otf",
  "Aileron-Bold.otf",
  "Aileron-HeavyItalic.otf",
  "Aileron-Heavy.otf",
  "Aileron-Italic.otf",
  "Aileron-LightItalic.otf",
  "Aileron-Light.otf",
  "Aileron-Regular.otf",
  "Aileron-SemiBoldItalic.otf",
  "Aileron-SemiBold.otf",
  "Aileron-ThinItalic.otf",
  "Aileron-Thin.otf",
  "Aileron-UltraLightItalic.otf",
  "Aileron-UltraLight.otf",
  "Air Americana.ttf",
  "Aladin-Regular.ttf",
  "Alegreya-BlackItalic.ttf",
  "Alegreya-Black.ttf",
  "Alegreya-BoldItalic.ttf",
  "Alegreya-Bold.ttf",
  "Alegreya-ExtraBoldItalic.ttf",
  "Alegreya-ExtraBold.ttf",
  "Alegreya-Italic.ttf",
  "Alegreya-MediumItalic.ttf",
  "Alegreya-Medium.ttf",
  "Alegreya-Regular.ttf",
  "AlegreyaSans-BlackItalic.ttf",
  "AlegreyaSans-Black.ttf",
  "AlegreyaSans-BoldItalic.ttf",
  "AlegreyaSans-Bold.ttf",
  "AlegreyaSans-ExtraBoldItalic.ttf",
  "AlegreyaSans-ExtraBold.ttf",
  "AlegreyaSans-Italic.ttf",
  "AlegreyaSans-LightItalic.ttf",
  "AlegreyaSans-Light.ttf",
  "AlegreyaSans-MediumItalic.ttf",
  "AlegreyaSans-Medium.ttf",
  "AlegreyaSans-Regular.ttf",
  "AlegreyaSans-ThinItalic.ttf",
  "AlegreyaSans-Thin.ttf",
  "AlegreyaSC-BlackItalic.ttf",
  "AlegreyaSC-Black.ttf",
  "AlegreyaSC-BoldItalic.ttf",
  "AlegreyaSC-Bold.ttf",
  "AlegreyaSC-ExtraBoldItalic.ttf",
  "AlegreyaSC-ExtraBold.ttf",
  "AlegreyaSC-Italic.ttf",
  "AlegreyaSC-MediumItalic.ttf",
  "AlegreyaSC-Medium.ttf",
  "AlegreyaSC-Regular.ttf",
  "Aliyah.ttf",
  "Allan-Bold.ttf",
  "Allan-Regular.ttf",
  "Alone On Earth.otf",
  "Amiko-Bold.ttf",
  "Amiko-Regular.ttf",
  "Amiko-SemiBold.ttf",
  "Among us 2.ttf",
  "Among us.ttf",
  "Anton-Regular.ttf",
  "ArchivoBlack-Regular.ttf",
  "ArimaMadurai-Black.ttf",
  "ArimaMadurai-Bold.ttf",
  "ArimaMadurai-ExtraBold.ttf",
  "ArimaMadurai-ExtraLight.ttf",
  "ArimaMadurai-Light.ttf",
  "ArimaMadurai-Medium.ttf",
  "ArimaMadurai-Regular.ttf",
  "ArimaMadurai-Thin.ttf",
  "Army Buster.otf",
  "Athletic.TTF",
  "Averus (DEMO).otf",
  "Averus (DEMO).ttf",
  "Ayudisha-Free-Version.ttf",
  "Baby Monsta Inner.otf",
  "Baby Monsta Shadow.otf",
  "Baby Monsta.otf",
  "BalooThambi-Regular.ttf",
  "Bangers-Regular.ttf",
  "BebasNeue Bold.otf",
  "BebasNeue Book.otf",
  "BebasNeue Book.ttf",
  "BebasNeue Light.otf",
  "BebasNeue Light.ttf",
  "BebasNeue Regular.otf",
  "BebasNeue Regular.ttf",
  "BebasNeue Thin.ttf",
  "BebasNeue.otf",
  "BebasTam.ttf",
  "BEBAS_.TTF",
  "Bellasya.otf",
  "Bellasya.ttf",
  "BillionDreams_PERSONAL.ttf",
  "BioRhyme-Bold.ttf",
  "BioRhyme-ExtraBold.ttf",
  "BioRhyme-ExtraLight.ttf",
  "BioRhyme-Light.ttf",
  "BioRhyme-Regular.ttf",
  "BlackOpsOne-Regular.ttf",
  "BlackSingature.otf",
  "BlackSingature.ttf",
  "Blacksword.otf",
  "BLINK SHARK.otf",
  "Bloomer DEMO.otf",
  "Blur.ttf",
  "BowlbyOne-Regular.ttf",
  "BowlbyOneSC-Regular.ttf",
  "Bubblegum.ttf",
  "budmo jiggler.ttf",
  "budmo jigglish.ttf",
  "Bungee-Regular.ttf",
  "BungeeShade-Regular.ttf",
  "Cabin-BoldItalic.ttf",
  "Cabin-Bold.ttf",
  "Cabin-Italic.ttf",
  "Cabin-MediumItalic.ttf",
  "Cabin-Medium.ttf",
  "Cabin-Regular.ttf",
  "Cabin-SemiBoldItalic.ttf",
  "Cabin-SemiBold.ttf",
  "Cambay-BoldItalic.ttf",
  "Cambay-Bold.ttf",
  "Cambay-Italic.ttf",
  "Cambay-Regular.ttf",
  "Candy Beans.otf",
  "Canter-Bold3D.otf",
  "Canter-Bold.otf",
  "Canter-BoldShadow.otf",
  "Canter-BoldStrips.otf",
  "Canter-Light.otf",
  "Canter-Outline.otf",
  "CarroisGothicSC-Regular.ttf",
  "CarterOne.ttf",
  "Cartoon cookies Tilted.otf",
  "Cartoon cookies Tilted.ttf",
  "Cartoon cookies.otf",
  "Cartoon cookies.ttf",
  "cartoonist_kooky.ttf",
  "Cartoon.ttf",
  "Casino3DFilled-Italic.ttf",
  "Casino3DFilledMarquee-Italic.ttf",
  "Casino3DFilledMarquee.ttf",
  "Casino3DFilled.ttf",
  "Casino3D-Italic.ttf",
  "Casino3DLines-Italic.ttf",
  "Casino3DLinesMarquee-Italic.ttf",
  "Casino3DLinesMarquee.ttf",
  "Casino3DLines.ttf",
  "Casino3DMarquee-Italic.ttf",
  "Casino3DMarquee.ttf",
  "Casino3D.ttf",
  "CasinoFlat-Italic.ttf",
  "CasinoFlatShadow-Italic.ttf",
  "CasinoFlatShadow.ttf",
  "CasinoFlat.ttf",
  "Casino-Italic.ttf",
  "CasinoShadow-Italic.ttf",
  "CasinoShadow.ttf",
  "Casino.ttf",
  "CevicheOne-Regular.ttf",
  "Chango-Regular.ttf",
  "ChelseaMarket-Regular.ttf",
  "Chunq.ttf",
  "Club de la pelea.ttf",
  "Cocogoose-Compressed-Bold-Italic-trial.ttf",
  "Cocogoose-Compressed-Bold-trial.ttf",
  "Cocogoose-Compressed-Letterpress-trial.ttf",
  "Cocogoose-Compressed-Light-Italic-trial.ttf",
  "Cocogoose-Compressed-Light-Trial.ttf",
  "Cocogoose-Compressed-Regular-italic-trial.ttf",
  "Cocogoose-Compressed-Regular-Trial.ttf",
  "Cocogoose-Compressed-Semilight-Italic-trial.ttf",
  "Cocogoose-Compressed-Semilight-Trial.ttf",
  "Cocogoose-Compressed-Thin-Italic-trial.ttf",
  "Cocogoose-Compressed-Thin-Trial.ttf",
  "Cocogoose-Compressed-Ultralight-Italic-trial.ttf",
  "Cocogoose-Compressed-UltraLight-Trial.ttf",
  "Cocogoose-Condensed-Letterpress-trial.ttf",
  "Cocogoose-Condensed-Light-Italic-trial.ttf",
  "Cocogoose-Condensed-Light-trial.ttf",
  "Cocogoose-Condensed-Regular-Italic-trial.ttf",
  "Cocogoose-Condensed-Regular-trial.ttf",
  "Cocogoose-Condensed-Semilight-Italic-trial.ttf",
  "Cocogoose-Condensed-Semilight-trial.ttf",
  "Cocogoose-Condensed-Thin-Italic-trial.ttf",
  "Cocogoose-Condensed-Thin-trial.ttf",
  "Cocogoose-Condensed-Ultralight-Italic-trial.ttf",
  "Cocogoose-Condensed-Ultralight-trial.ttf",
  "Cocogoose-Narrow-Letterpress-trial.ttf",
  "Cocogoose-Narrow-Light-Italic-trial.ttf",
  "Cocogoose-Narrow-Light-trial.ttf",
  "Cocogoose-Narrow-Regular-Italic-trial.ttf",
  "Cocogoose-Narrow-Regular-trial.ttf",
  "Cocogoose-Narrow-Semilight-Italic-trial.ttf",
  "Cocogoose-Narrow-Semilight-trial.ttf",
  "Cocogoose-Narrow-Thin-Italic-trial.ttf",
  "Cocogoose-Narrow-Thin-trial.ttf",
  "Cocogoose-Narrow-Ultralight-Italic-trial.ttf",
  "Cocogoose-Narrow-Ultralight-trial.ttf",
  "Coconut Cookies.ttf",
  "COD.otf",
  "Comic Kings.otf",
  "Comic Kings.ttf",
  "Comic.TTF",
  "ComingSoon-Regular.ttf",
  "Comix Loud.ttf",
  "Cormorant-BoldItalic.ttf",
  "Cormorant-Bold.ttf",
  "CormorantGaramond-BoldItalic.ttf",
  "CormorantGaramond-Bold.ttf",
  "CormorantGaramond-Italic.ttf",
  "CormorantGaramond-LightItalic.ttf",
  "CormorantGaramond-Light.ttf",
  "CormorantGaramond-MediumItalic.ttf",
  "CormorantGaramond-Medium.ttf",
  "CormorantGaramond-Regular.ttf",
  "CormorantGaramond-SemiBoldItalic.ttf",
  "CormorantGaramond-SemiBold.ttf",
  "Cormorant-Italic.ttf",
  "Cormorant-LightItalic.ttf",
  "Cormorant-Light.ttf",
  "Cormorant-MediumItalic.ttf",
  "Cormorant-Medium.ttf",
  "Cormorant-Regular.ttf",
  "Cormorant-SemiBoldItalic.ttf",
  "Cormorant-SemiBold.ttf",
  "CoveredByYourGrace.ttf",
  "Creepster-Regular.ttf",
  "Demode-Negative.ttf",
  "Demode.ttf",
  "DenkOne-Regular.ttf",
  "Dimbo Italic.ttf",
  "Dimbo Regular.ttf",
  "DIMIS___.TTF",
  "DIMITRI_.TTF",
  "Distorsion 2.otf",
  "Distorsión.ttf",
  "Dokdo-Regular.ttf",
  "Dot Spot.ttf",
  "Drifttype Solid.ttf",
  "Drifttype.ttf",
  "Eighties FREE.otf",
  "Eighties FREE.ttf",
  "EmilysCandy-Regular.ttf",
  "EricaOne-Regular.ttf",
  "Ewert-Regular.ttf",
  "ExtraBlur.ttf",
  "f02.TTF",
  "f06.TTF",
  "f08.TTF",
  "f10.TTF",
  "f23.TTF",
  "f38.TTF",
  "f39.TTF",
  "f43.TTF",
  "f5.TTF",
  "FALL GUYS.ttf",
  "Farsan-Regular.ttf",
  "FasterOne-Regular.ttf",
  "FE11003T.TTF",
  "FE11004T.TTF",
  "FE11006T.TTF",
  "FE11042T.TTF",
  "FE11044T.TTF",
  "FE11046T.TTF",
  "Feral-Regular.ttf",
  "FontdinerSwanky-Regular.ttf",
  "Fortnite.ttf",
  "FranchiseFilled.ttf",
  "Franchise.ttf",
  "FrancoisOne-Regular.ttf",
  "FreckleFace-Regular.ttf",
  "FredokaOne-Regular.ttf",
  "Free fire.otf",
  "Fresca-Regular.ttf",
  "Fruktur-Regular.ttf",
  "FUTRFW.TTF",
  "FutuBdIt.ttf",
  "FutuBd__.ttf",
  "FutuBkIt.ttf",
  "FutuBk__.ttf",
  "FutuHvIt.ttf",
  "FutuHv__.ttf",
  "FutuLtIt.ttf",
  "FutuLt__.ttf",
  "FutuMdIt.ttf",
  "FutuMd__.ttf",
  "Futura  Book.TTF",
  "Futura 2 Ital.TTF",
  "Futura 2 Normal.TTF",
  "Futura Black BT.ttf",
  "Futura Bold BT.ttf",
  "Futura Bold Italic BT.ttf",
  "Futura Bold Obl.TTF",
  "Futura Bold.TTF",
  "Futura Cnd Bold Ital.TTF",
  "Futura Cnd Bold.TTF",
  "Futura Cnd Extra Bold Thin.TTF",
  "Futura Cnd Ital.TTF",
  "Futura Cnd Norma.TTF",
  "Futura Cnd Obl Bo.TTF",
  "Futura Cnd Obl No.TTF",
  "Futura Ext Obl Bold.TTF",
  "Futura Ext Obl No.TTF",
  "Futura Extra Black BT.ttf",
  "Futura Light BT.ttf",
  "Futura Light Italic BT.ttf",
  "Futura Normal.TTF",
  "Futura Obl Bold.TTF",
  "Futura Obl Normal.TTF",
  "Futura Poster Light.TTF",
  "Futura Thin.TTF",
  "Futurabc.ttf",
  "Futurahi.ttf",
  "Futurah.ttf",
  "Futuralc.ttf",
  "Futuramc.ttf",
  "Futurami.ttf",
  "Futuram.ttf",
  "Futurani.ttf",
  "Futuran.ttf",
  "Futura.ttf",
  "Futurbci.ttf",
  "Future Sallow Wide.ttf",
  "Future Sallow.ttf",
  "Futured.ttf",
  "FUTURE.ttf",
  "Futurex Apocalypse.ttf",
  "Futurex Phat Italic.ttf",
  "Futurex Phat Outline Italic.ttf",
  "Futurex Phat Outline.ttf",
  "Futurex Phat.ttf",
  "Futurex Voyager.ttf",
  "FuturexBob.ttf",
  "Futurism.ttf",
  "Futurist ExtraHeavy Regular.ttf",
  "FuturistBlack Regular.ttf",
  "FuturistExtraHeavy Italic.ttf",
  "Futurist-Stencil Regular.ttf",
  "Futurlci.ttf",
  "Futurmci.ttf",
  "Futurxkc.ttf",
  "Futurxki.ttf",
  "Futuxkci.ttf",
  "Gameplay.ttf",
  "GIN_AND_SODA_PERSONAL_USE.ttf",
  "Glamor-BoldCondensedItalic.otf",
  "Glamor-BoldCondensed.otf",
  "Glamor-BoldExtendedItalic.otf",
  "Glamor-BoldExtended.otf",
  "Glamor-BoldItalic.otf",
  "Glamor-Bold.otf",
  "Glamor-CondensedItalic.otf",
  "Glamor-Condensed.otf",
  "Glamor-ExtendedItalic.otf",
  "Glamor-Extended.otf",
  "Glamor-Italic.otf",
  "Glamor-LightCondensedItalic.otf",
  "Glamor-LightCondensed.otf",
  "Glamor-LightExtendedItalic.otf",
  "Glamor-LightExtended.otf",
  "Glamor-LightItalic.otf",
  "Glamor-Light.otf",
  "Glamor-MediumCondensedItali.otf",
  "Glamor-MediumCondensed.otf",
  "Glamor-MediumExtendedItalic.otf",
  "Glamor-MediumExtended.otf",
  "Glamor-MediumItalic.otf",
  "Glamor-Medium.otf",
  "Glamor-Regular.otf",
  "Glitch 2.otf",
  "Glitch.ttf",
  "GochiHand-Regular.ttf",
  "Godzilla.ttf",
  "GravitasOne.ttf",
  "GROBOLD.ttf",
  "Grounge.ttf",
  "GTA.TTF",
  "Hallo sans black.otf",
  "Hallo sans light.otf",
  "Hallo sans.otf",
  "Halo.ttf",
  "hansolov3_3dital.ttf",
  "hansolov3_3d.ttf",
  "hansolov3acadital.ttf",
  "hansolov3acad.ttf",
  "hansolov3condital.ttf",
  "hansolov3cond.ttf",
  "hansolov3expandital.ttf",
  "hansolov3expand.ttf",
  "hansolov3gradital.ttf",
  "hansolov3grad.ttf",
  "hansolov3halfital.ttf",
  "hansolov3half.ttf",
  "hansolov3ital.ttf",
  "hansolov3laserital.ttf",
  "hansolov3laser.ttf",
  "hansolov3left.ttf",
  "hansolov3outital.ttf",
  "hansolov3out.ttf",
  "hansolov3overital.ttf",
  "hansolov3over.ttf",
  "hansolov3platital.ttf",
  "hansolov3plat.ttf",
  "hansolov3.ttf",
  "Hello Sunshine.otf",
  "Hello Sunshine.ttf",
  "IBMPlexMono-BoldItalic.ttf",
  "IBMPlexMono-Bold.ttf",
  "IBMPlexMono-ExtraLightItalic.ttf",
  "IBMPlexMono-ExtraLight.ttf",
  "IBMPlexMono-Italic.ttf",
  "IBMPlexMono-LightItalic.ttf",
  "IBMPlexMono-Light.ttf",
  "IBMPlexMono-MediumItalic.ttf",
  "IBMPlexMono-Medium.ttf",
  "IBMPlexMono-Regular.ttf",
  "IBMPlexMono-SemiBoldItalic.ttf",
  "IBMPlexMono-SemiBold.ttf",
  "IBMPlexMono-ThinItalic.ttf",
  "IBMPlexMono-Thin.ttf",
  "JosefinSans-BoldItalic.ttf",
  "JosefinSans-Bold.ttf",
  "JosefinSans-Italic.ttf",
  "JosefinSans-LightItalic.ttf",
  "JosefinSans-Light.ttf",
  "JosefinSans-Regular.ttf",
  "JosefinSans-SemiBoldItalic.ttf",
  "JosefinSans-SemiBold.ttf",
  "JosefinSans-ThinItalic.ttf",
  "JosefinSans-Thin.ttf",
  "Jua-Regular.ttf",
  "Jungle Land.ttf",
  "Jurassic park.ttf",
  "JustAnotherHand-Regular.ttf",
  "K2D-BoldItalic.ttf",
  "K2D-Bold.ttf",
  "K2D-ExtraBoldItalic.ttf",
  "K2D-ExtraBold.ttf",
  "K2D-ExtraLightItalic.ttf",
  "K2D-ExtraLight.ttf",
  "K2D-Italic.ttf",
  "K2D-LightItalic.ttf",
  "K2D-Light.ttf",
  "K2D-MediumItalic.ttf",
  "K2D-Medium.ttf",
  "K2D-Regular.ttf",
  "K2D-SemiBoldItalic.ttf",
  "K2D-SemiBold.ttf",
  "K2D-ThinItalic.ttf",
  "K2D-Thin.ttf",
  "Ka Blam Under.ttf",
  "Ka Blam.ttf",
  "Kanit-BlackItalic.ttf",
  "Kanit-Black.ttf",
  "Kanit-BoldItalic.ttf",
  "Kanit-Bold.ttf",
  "Kanit-ExtraBoldItalic.ttf",
  "Kanit-ExtraBold.ttf",
  "Kanit-ExtraLightItalic.ttf",
  "Kanit-ExtraLight.ttf",
  "Kanit-Italic.ttf",
  "Kanit-LightItalic.ttf",
  "Kanit-Light.ttf",
  "Kanit-MediumItalic.ttf",
  "Kanit-Medium.ttf",
  "Kanit-Regular.ttf",
  "Kanit-SemiBoldItalic.ttf",
  "Kanit-SemiBold.ttf",
  "Kanit-ThinItalic.ttf",
  "Kanit-Thin.ttf",
  "Kavoon-Regular.ttf",
  "Knewave-Regular.ttf",
  "LondrinaSolid-Black.ttf",
  "LondrinaSolid-Light.ttf",
  "LondrinaSolid-Regular.ttf",
  "LondrinaSolid-Thin.ttf",
  "Lora-BoldItalic.ttf",
  "Lora-Bold.ttf",
  "Lora-Italic.ttf",
  "Lora-Regular.ttf",
  "LuckiestGuy-Regular.ttf",
  "Magic Dreams.ttf",
  "MeriendaOne-Regular.ttf",
  "Michroma.ttf",
  "Minecraft-Bold.otf",
  "Modak-Regular.ttf",
  "MUSICNET.ttf",
  "NanumBrushScript-Regular.ttf",
  "Naruto.ttf",
  "Nature Beauty Personal Use.ttf",
  "Neon 3d.ttf",
  "Neon.ttf",
  "NexaRustExtras-Free.otf",
  "NexaRustHandmade-Extended.otf",
  "NexaRustSans-Black.otf",
  "NexaRustScriptL-0.otf",
  "NexaRustSlab-BlackShadow01.otf",
  "norwester.otf",
  "Nunito-BlackItalic.ttf",
  "Nunito-Black.ttf",
  "Nunito-BoldItalic.ttf",
  "Nunito-Bold.ttf",
  "Nunito-ExtraBoldItalic.ttf",
  "Nunito-ExtraBold.ttf",
  "Nunito-ExtraLightItalic.ttf",
  "Nunito-ExtraLight.ttf",
  "Nunito-Italic.ttf",
  "Nunito-LightItalic.ttf",
  "Nunito-Light.ttf",
  "Nunito-Regular.ttf",
  "Nunito-SemiBoldItalic.ttf",
  "Nunito-SemiBold.ttf",
  "Old school.ttf",
  "Oswald-Bold.ttf",
  "Oswald-ExtraLight.ttf",
  "Oswald-Light.ttf",
  "Oswald-Medium.ttf",
  "Oswald-Regular.ttf",
  "Oswald-SemiBold.ttf",
  "Outrun future Bold Italic.otf",
  "Outrun future Bold.otf",
  "Outrun future.otf",
  "PassionOne-Black.ttf",
  "PassionOne-Bold.ttf",
  "PassionOne-Regular.ttf",
  "PermanentMarker-Regular.ttf",
  "Pincel.ttf",
  "Planet Of The Apes.ttf",
  "Poppins-BlackItalic.ttf",
  "Poppins-Black.ttf",
  "Poppins-BoldItalic.ttf",
  "Poppins-Bold.ttf",
  "Poppins-ExtraBoldItalic.ttf",
  "Poppins-ExtraBold.ttf",
  "Poppins-ExtraLightItalic.ttf",
  "Poppins-ExtraLight.ttf",
  "Poppins-Italic.ttf",
  "Poppins-LightItalic.ttf",
  "Poppins-Light.ttf",
  "Poppins-MediumItalic.ttf",
  "Poppins-Medium.ttf",
  "Poppins-Regular.ttf",
  "Poppins-SemiBoldItalic.ttf",
  "Poppins-SemiBold.ttf",
  "Poppins-ThinItalic.ttf",
  "Poppins-Thin.ttf",
  "PressStart2P-Regular.ttf",
  "Questrial-Regular.ttf",
  "Questrian.otf",
  "RacingSansOne-Regular.ttf",
  "Ralliankara Personal Use Only.otf",
  "Ralliankara Personal Use Only.ttf",
  "Righteous-Regular.ttf",
  "Road_Rage.otf",
  "Roblox.ttf",
  "RubikMonoOne-Regular.ttf",
  "RumRaisin-Regular.ttf",
  "SallimSignature.otf",
  "SallimSignature.ttf",
  "Schoolbell-Regular.ttf",
  "SedgwickAveDisplay-Regular.ttf",
  "SedgwickAve-Regular.ttf",
  "SEGA.TTF",
  "SFProDisplay-Black.ttf",
  "SFProDisplay-Bold.ttf",
  "SFProDisplay-Heavy.ttf",
  "SFProDisplay-Light.ttf",
  "SFProDisplay-Medium.ttf",
  "SFProDisplay-Regular.ttf",
  "SFProDisplay-Semibold.ttf",
  "SFProDisplay-Thin.ttf",
  "SFProDisplay-Ultralight.ttf",
  "SFProText-Bold.ttf",
  "SFProText-Heavy.ttf",
  "SFProText-Light.ttf",
  "SFProText-Medium.ttf",
  "SFProText-Regular.ttf",
  "SFProText-Semibold.ttf",
  "ShortStack-Regular.ttf",
  "Shrikhand-Regular.ttf",
  "SigmarOne-Regular.ttf",
  "Sillii Willinn Font.ttf",
  "SIMPLICITY PERSONALUSE.ttf",
  "SIMPLICITY SHADOW PERSONAL USE.ttf",
  "Simplicity.otf",
  "Simplicity.ttf",
  "Sin_City.ttf",
  "sing_14l.ttf",
  "Slackey-Regular.ttf",
  "soloist1.ttf",
  "soloist3d.ttf",
  "soloistacad.ttf",
  "soloistchrome.ttf",
  "soloistcond1.ttf",
  "soloistexpand1.ttf",
  "soloistextraital1.ttf",
  "soloistgrad1.ttf",
  "soloisthalf1.ttf",
  "soloisthalf21.ttf",
  "soloisthalf.ttf",
  "soloistital1.ttf",
  "soloistlaser1.ttf",
  "soloistlaserital1.ttf",
  "soloistleft1.ttf",
  "soloistout.ttf",
  "soloiststraight1.ttf",
  "soloisttitle1.ttf",
  "soupofjustice.ttf",
  "speedwagon3dital.ttf",
  "speedwagon3d.ttf",
  "speedwagoncondital.ttf",
  "speedwagoncond.ttf",
  "speedwagonexpandital.ttf",
  "speedwagonexpand.ttf",
  "speedwagonhalfital.ttf",
  "speedwagonhalf.ttf",
  "speedwagonital.ttf",
  "speedwagonlaserital.ttf",
  "speedwagonlaser.ttf",
  "speedwagonleft.ttf",
  "speedwagonsuperital.ttf",
  "speedwagon.ttf",
  "speedwagonxtraexpandital.ttf",
  "speedwagonxtraexpand.ttf",
  "SpicyRice-Regular.ttf",
  "Splatch.ttf",
  "Squirk.otf",
  "Star Wars.ttf",
  "Starborn.otf",
  "Starborn.ttf",
  "Stella Demo.otf",
  "Stella Demo.ttf",
  "strude.ttf",
  "SugarpunchDEMO.otf",
  "Summer Splash Display.otf",
  "Summer Splash.otf",
  "Sunkist Squash.otf",
  "Sunkist Squash.ttf",
  "Super Comic.otf",
  "Super Mario.TTF",
  "Supercell-magic-webfont.ttf",
  "sweet purple.otf",
  "sweet purple.ttf",
  "Teko-Bold.ttf",
  "Teko-Light.ttf",
  "Teko-Medium.ttf",
  "Teko-Regular.ttf",
  "Teko-SemiBold.ttf",
  "The Blacklist.ttf",
  "TitanOne-Regular.ttf",
  "Toxico.otf",
  "TradeWinds-Regular.ttf",
  "TT0206C_.TTF",
  "Unicorn Pop.otf",
  "Unicorn Pop.ttf",
  "usuzi3dital.ttf",
  "usuzi3d.ttf",
  "usuziboldital.ttf",
  "usuzibold.ttf",
  "usuzicondital.ttf",
  "usuzicond.ttf",
  "usuziexpandital.ttf",
  "usuziexpand.ttf",
  "usuzigradital.ttf",
  "usuzigrad.ttf",
  "usuzihalfital.ttf",
  "usuzihalf.ttf",
  "usuziital.ttf",
  "usuzileft.ttf",
  "usuzisemital.ttf",
  "usuzi.ttf",
  "VTC- GarageSaleOutlined.ttf",
  "VTC-GarageSale.otf",
  "VTC-GarageSaleOutlined.otf",
  "VTC-GarageSale.ttf",
  "WalterTurncoat-Regular.ttf",
  "WendyOne-Regular.ttf",
  "White On Black.ttf",
  "Wicked Mouse Demo.otf",
  "ZCOOLKuaiLe-Regular.ttf",
];
const fs = require("fs");

const fonts = Fonts_list.reduce((acc, font) => {
  const fontName = font.replace(/\.(otf|ttf)$/, "");
  acc[fontName] = `require("./assets/fonts/${font}")`;
  return acc;
}, {});

const jsonFonts = JSON.stringify(fonts, null, 2);

fs.writeFileSync("./fonts.json", jsonFonts);

console.log("Archivo JSON de fuentes creado exitosamente.");