export const Fonts_list = [
  "Abel-Regular",
  "Academic M54",
  "Acids!",
  "Raleway-Light",
  "Raleway-Medium",
  "Aileron-BlackItalic",
  "Aileron-Black",
  "Aileron-BoldItalic",
  "Aileron-Bold",
  "Aileron-HeavyItalic",
  "Aileron-Heavy",
  "Aileron-Italic",
  "Aileron-LightItalic",
  "Aileron-Light",
  "Aileron-Regular",
  "Aileron-SemiBoldItalic",
  "Aileron-SemiBold",
  "Aileron-ThinItalic",
  "Aileron-Thin",
  "Aileron-UltraLightItalic",
  "Aileron-UltraLight",
  "Air Americana",
  "Aladin-Regular",
  "Alegreya-BlackItalic",
  "Alegreya-Black",
  "Alegreya-BoldItalic",
  "Alegreya-Bold",
  "Alegreya-ExtraBoldItalic",
  "Alegreya-ExtraBold",
  "Alegreya-Italic",
  "Alegreya-MediumItalic",
  "Alegreya-Medium",
  "Alegreya-Regular",
  "AlegreyaSans-BlackItalic",
  "AlegreyaSans-Black",
  "AlegreyaSans-BoldItalic",
  "AlegreyaSans-Bold",
  "AlegreyaSans-ExtraBoldItalic",
  "AlegreyaSans-ExtraBold",
  "AlegreyaSans-Italic",
  "AlegreyaSans-LightItalic",
  "AlegreyaSans-Light",
  "AlegreyaSans-MediumItalic",
  "AlegreyaSans-Medium",
  "AlegreyaSans-Regular",
  "AlegreyaSans-ThinItalic",
  "AlegreyaSans-Thin",
  "AlegreyaSC-BlackItalic",
  "AlegreyaSC-Black",
  "AlegreyaSC-BoldItalic",
  "AlegreyaSC-Bold",
  "AlegreyaSC-ExtraBoldItalic",
  "AlegreyaSC-ExtraBold",
  "AlegreyaSC-Italic",
  "AlegreyaSC-MediumItalic",
  "AlegreyaSC-Medium",
  "AlegreyaSC-Regular",
  "Aliyah",
  "Allan-Bold",
  "Allan-Regular",
  "Alone On Earth",
  "Amiko-Bold",
  "Amiko-Regular",
  "Amiko-SemiBold",
  "Among us 2",
  "Among us",
  "Anton-Regular",
  "ArchivoBlack-Regular",
  "ArimaMadurai-Black",
  "ArimaMadurai-Bold",
  "ArimaMadurai-ExtraBold",
  "ArimaMadurai-ExtraLight",
  "ArimaMadurai-Light",
  "ArimaMadurai-Medium",
  "ArimaMadurai-Regular",
  "ArimaMadurai-Thin",
  "Army Buster",
  "Averus (DEMO)",
  "Averus (DEMO)",
  "Ayudisha-Free-Version",
  "Baby Monsta Inner",
  "Baby Monsta Shadow",
  "Baby Monsta",
  "BalooThambi-Regular",
  "Bangers-Regular",
  "BebasNeue Bold",
  "BebasNeue Book",
  "BebasNeue Book",
  "BebasNeue Light",
  "BebasNeue Light",
  "BebasNeue Regular",
  "BebasNeue Regular",
  "BebasNeue Thin",
  "BebasNeue",
  "BebasTam",
  "Bellasya",
  "Bellasya",
  "BillionDreams_PERSONAL",
  "BioRhyme-Bold",
  "BioRhyme-ExtraBold",
  "BioRhyme-ExtraLight",
  "BioRhyme-Light",
  "BioRhyme-Regular",
  "BlackOpsOne-Regular",
  "BlackSingature",
  "BlackSingature",
  "Blacksword",
  "BLINK SHARK",
  "Bloomer DEMO",
  "Blur",
  "BowlbyOne-Regular",
  "BowlbyOneSC-Regular",
  "Bubblegum",
  "budmo jiggler",
  "budmo jigglish",
  "Bungee-Regular",
  "BungeeShade-Regular",
  "Cabin-BoldItalic",
  "Cabin-Bold",
  "Cabin-Italic",
  "Cabin-MediumItalic",
  "Cabin-Medium",
  "Cabin-Regular",
  "Cabin-SemiBoldItalic",
  "Cabin-SemiBold",
  "Cambay-BoldItalic",
  "Cambay-Bold",
  "Cambay-Italic",
  "Cambay-Regular",
  "Candy Beans",
  "Canter-Bold3D",
  "Canter-Bold",
  "Canter-BoldShadow",
  "Canter-BoldStrips",
  "Canter-Light",
  "Canter-Outline",
  "CarroisGothicSC-Regular",
  "CarterOne",
  "Cartoon cookies Tilted",
  "Cartoon cookies Tilted",
  "Cartoon cookies",
  "Cartoon cookies",
  "cartoonist_kooky",
  "Cartoon",
  "Casino3DFilled-Italic",
  "Casino3DFilledMarquee-Italic",
  "Casino3DFilledMarquee",
  "Casino3DFilled",
  "Casino3D-Italic",
  "Casino3DLines-Italic",
  "Casino3DLinesMarquee-Italic",
  "Casino3DLinesMarquee",
  "Casino3DLines",
  "Casino3DMarquee-Italic",
  "Casino3DMarquee",
  "Casino3D",
  "CasinoFlat-Italic",
  "CasinoFlatShadow-Italic",
  "CasinoFlatShadow",
  "CasinoFlat",
  "Casino-Italic",
  "CasinoShadow-Italic",
  "CasinoShadow",
  "Casino",
  "CevicheOne-Regular",
  "Chango-Regular",
  "ChelseaMarket-Regular",
  "Chunq",
  "Club de la pelea",
  "Cocogoose-Compressed-Bold-Italic-trial",
  "Cocogoose-Compressed-Bold-trial",
  "Cocogoose-Compressed-Letterpress-trial",
  "Cocogoose-Compressed-Light-Italic-trial",
  "Cocogoose-Compressed-Light-Trial",
  "Cocogoose-Compressed-Regular-italic-trial",
  "Cocogoose-Compressed-Regular-Trial",
  "Cocogoose-Compressed-Semilight-Italic-trial",
  "Cocogoose-Compressed-Semilight-Trial",
  "Cocogoose-Compressed-Thin-Italic-trial",
  "Cocogoose-Compressed-Thin-Trial",
  "Cocogoose-Compressed-Ultralight-Italic-trial",
  "Cocogoose-Compressed-UltraLight-Trial",
  "Cocogoose-Condensed-Letterpress-trial",
  "Cocogoose-Condensed-Light-Italic-trial",
  "Cocogoose-Condensed-Light-trial",
  "Cocogoose-Condensed-Regular-Italic-trial",
  "Cocogoose-Condensed-Regular-trial",
  "Cocogoose-Condensed-Semilight-Italic-trial",
  "Cocogoose-Condensed-Semilight-trial",
  "Cocogoose-Condensed-Thin-Italic-trial",
  "Cocogoose-Condensed-Thin-trial",
  "Cocogoose-Condensed-Ultralight-Italic-trial",
  "Cocogoose-Condensed-Ultralight-trial",
  "Cocogoose-Narrow-Letterpress-trial",
  "Cocogoose-Narrow-Light-Italic-trial",
  "Cocogoose-Narrow-Light-trial",
  "Cocogoose-Narrow-Regular-Italic-trial",
  "Cocogoose-Narrow-Regular-trial",
  "Cocogoose-Narrow-Semilight-Italic-trial",
  "Cocogoose-Narrow-Semilight-trial",
  "Cocogoose-Narrow-Thin-Italic-trial",
  "Cocogoose-Narrow-Thin-trial",
  "Cocogoose-Narrow-Ultralight-Italic-trial",
  "Cocogoose-Narrow-Ultralight-trial",
  "Coconut Cookies",
  "COD",
  "Comic Kings",
  "Comic Kings",

  "ComingSoon-Regular",
  "Comix Loud",
  "Cormorant-BoldItalic",
  "Cormorant-Bold",
  "CormorantGaramond-BoldItalic",
  "CormorantGaramond-Bold",
  "CormorantGaramond-Italic",
  "CormorantGaramond-LightItalic",
  "CormorantGaramond-Light",
  "CormorantGaramond-MediumItalic",
  "CormorantGaramond-Medium",
  "CormorantGaramond-Regular",
  "CormorantGaramond-SemiBoldItalic",
  "CormorantGaramond-SemiBold",
  "Cormorant-Italic",
  "Cormorant-LightItalic",
  "Cormorant-Light",
  "Cormorant-MediumItalic",
  "Cormorant-Medium",
  "Cormorant-Regular",
  "Cormorant-SemiBoldItalic",
  "Cormorant-SemiBold",
  "CoveredByYourGrace",
  "Creepster-Regular",
  "Demode-Negative",
  "Demode",
  "DenkOne-Regular",
  "Dimbo Italic",
  "Dimbo Regular",

  "Distorsion 2",
  "Distorsión",
  "Dokdo-Regular",
  "Dot Spot",
  "Drifttype Solid",
  "Drifttype",
  "Eighties FREE",
  "Eighties FREE",
  "EmilysCandy-Regular",
  "EricaOne-Regular",
  "Ewert-Regular",
  "ExtraBlur",

  "FALL GUYS",
  "Farsan-Regular",
  "FasterOne-Regular",

  "Feral-Regular",
  "FontdinerSwanky-Regular",
  "Fortnite",
  "FranchiseFilled",
  "Franchise",
  "FrancoisOne-Regular",
  "FreckleFace-Regular",
  "FredokaOne-Regular",
  "Free fire",
  "Fresca-Regular",
  "Fruktur-Regular",

  "FutuBdIt",
  "FutuBd__",
  "FutuBkIt",
  "FutuBk__",
  "FutuHvIt",
  "FutuHv__",
  "FutuLtIt",
  "FutuLt__",
  "FutuMdIt",
  "FutuMd__",

  "Futura Black BT",
  "Futura Bold BT",
  "Futura Bold Italic BT",

  "Futura Extra Black BT",
  "Futura Light BT",
  "Futura Light Italic BT",
  "Futurabc",
  "Futurahi",
  "Futurah",
  "Futuralc",
  "Futuramc",
  "Futurami",
  "Futuram",
  "Futurani",
  "Futuran",
  "Futura",
  "Futurbci",
  "Future Sallow Wide",
  "Future Sallow",
  "Futured",
  "FUTURE",
  "Futurex Apocalypse",
  "Futurex Phat Italic",
  "Futurex Phat Outline Italic",
  "Futurex Phat Outline",
  "Futurex Phat",
  "Futurex Voyager",
  "FuturexBob",
  "Futurism",
  "Futurist ExtraHeavy Regular",
  "FuturistBlack Regular",
  "FuturistExtraHeavy Italic",
  "Futurist-Stencil Regular",
  "Futurlci",
  "Futurmci",
  "Futurxkc",
  "Futurxki",
  "Futuxkci",
  "Gameplay",
  "GIN_AND_SODA_PERSONAL_USE",
  "Glamor-BoldCondensedItalic",
  "Glamor-BoldCondensed",
  "Glamor-BoldExtendedItalic",
  "Glamor-BoldExtended",
  "Glamor-BoldItalic",
  "Glamor-Bold",
  "Glamor-CondensedItalic",
  "Glamor-Condensed",
  "Glamor-ExtendedItalic",
  "Glamor-Extended",
  "Glamor-Italic",
  "Glamor-LightCondensedItalic",
  "Glamor-LightCondensed",
  "Glamor-LightExtendedItalic",
  "Glamor-LightExtended",
  "Glamor-LightItalic",
  "Glamor-Light",
  "Glamor-MediumCondensedItali",
  "Glamor-MediumCondensed",
  "Glamor-MediumExtendedItalic",
  "Glamor-MediumExtended",
  "Glamor-MediumItalic",
  "Glamor-Medium",
  "Glamor-Regular",
  "Glitch 2",
  "Glitch",
  "GochiHand-Regular",
  "Godzilla",
  "GravitasOne",
  "GROBOLD",
  "Grounge",
  "Hallo sans black",
  "Hallo sans light",
  "Hallo sans",
  "Halo",
  "hansolov3_3dital",
  "hansolov3_3d",
  "hansolov3acadital",
  "hansolov3acad",
  "hansolov3condital",
  "hansolov3cond",
  "hansolov3expandital",
  "hansolov3expand",
  "hansolov3gradital",
  "hansolov3grad",
  "hansolov3halfital",
  "hansolov3half",
  "hansolov3ital",
  "hansolov3laserital",
  "hansolov3laser",
  "hansolov3left",
  "hansolov3outital",
  "hansolov3out",
  "hansolov3overital",
  "hansolov3over",
  "hansolov3platital",
  "hansolov3plat",
  "hansolov3",
  "Hello Sunshine",
  "Hello Sunshine",
  "IBMPlexMono-BoldItalic",
  "IBMPlexMono-Bold",
  "IBMPlexMono-ExtraLightItalic",
  "IBMPlexMono-ExtraLight",
  "IBMPlexMono-Italic",
  "IBMPlexMono-LightItalic",
  "IBMPlexMono-Light",
  "IBMPlexMono-MediumItalic",
  "IBMPlexMono-Medium",
  "IBMPlexMono-Regular",
  "IBMPlexMono-SemiBoldItalic",
  "IBMPlexMono-SemiBold",
  "IBMPlexMono-ThinItalic",
  "IBMPlexMono-Thin",
  "JosefinSans-BoldItalic",
  "JosefinSans-Bold",
  "JosefinSans-Italic",
  "JosefinSans-LightItalic",
  "JosefinSans-Light",
  "JosefinSans-Regular",
  "JosefinSans-SemiBoldItalic",
  "JosefinSans-SemiBold",
  "JosefinSans-ThinItalic",
  "JosefinSans-Thin",
  "Jua-Regular",
  "Jungle Land",
  "Jurassic park",
  "JustAnotherHand-Regular",
  "K2D-BoldItalic",
  "K2D-Bold",
  "K2D-ExtraBoldItalic",
  "K2D-ExtraBold",
  "K2D-ExtraLightItalic",
  "K2D-ExtraLight",
  "K2D-Italic",
  "K2D-LightItalic",
  "K2D-Light",
  "K2D-MediumItalic",
  "K2D-Medium",
  "K2D-Regular",
  "K2D-SemiBoldItalic",
  "K2D-SemiBold",
  "K2D-ThinItalic",
  "K2D-Thin",
  "Ka Blam Under",
  "Ka Blam",
  "Kanit-BlackItalic",
  "Kanit-Black",
  "Kanit-BoldItalic",
  "Kanit-Bold",
  "Kanit-ExtraBoldItalic",
  "Kanit-ExtraBold",
  "Kanit-ExtraLightItalic",
  "Kanit-ExtraLight",
  "Kanit-Italic",
  "Kanit-LightItalic",
  "Kanit-Light",
  "Kanit-MediumItalic",
  "Kanit-Medium",
  "Kanit-Regular",
  "Kanit-SemiBoldItalic",
  "Kanit-SemiBold",
  "Kanit-ThinItalic",
  "Kanit-Thin",
  "Kavoon-Regular",
  "Knewave-Regular",
  "LondrinaSolid-Black",
  "LondrinaSolid-Light",
  "LondrinaSolid-Regular",
  "LondrinaSolid-Thin",
  "Lora-BoldItalic",
  "Lora-Bold",
  "Lora-Italic",
  "Lora-Regular",
  "LuckiestGuy-Regular",
  "Magic Dreams",
  "MeriendaOne-Regular",
  "Michroma",
  "Minecraft-Bold",
  "Modak-Regular",
  "MUSICNET",
  "NanumBrushScript-Regular",
  "Naruto",
  "Nature Beauty Personal Use",
  "Neon 3d",
  "Neon",
  "NexaRustExtras-Free",
  "NexaRustHandmade-Extended",
  "NexaRustSans-Black",
  "NexaRustScriptL-0",
  "NexaRustSlab-BlackShadow01",
  "norwester",
  "Nunito-BlackItalic",
  "Nunito-Black",
  "Nunito-BoldItalic",
  "Nunito-Bold",
  "Nunito-ExtraBoldItalic",
  "Nunito-ExtraBold",
  "Nunito-ExtraLightItalic",
  "Nunito-ExtraLight",
  "Nunito-Italic",
  "Nunito-LightItalic",
  "Nunito-Light",
  "Nunito-Regular",
  "Nunito-SemiBoldItalic",
  "Nunito-SemiBold",
  "Old school",
  "Oswald-Bold",
  "Oswald-ExtraLight",
  "Oswald-Light",
  "Oswald-Medium",
  "Oswald-Regular",
  "Oswald-SemiBold",
  "Outrun future Bold Italic",
  "Outrun future Bold",
  "Outrun future",
  "PassionOne-Black",
  "PassionOne-Bold",
  "PassionOne-Regular",
  "PermanentMarker-Regular",
  "Pincel",
  "Planet Of The Apes",
  "Poppins-BlackItalic",
  "Poppins-Black",
  "Poppins-BoldItalic",
  "Poppins-Bold",
  "Poppins-ExtraBoldItalic",
  "Poppins-ExtraBold",
  "Poppins-ExtraLightItalic",
  "Poppins-ExtraLight",
  "Poppins-Italic",
  "Poppins-LightItalic",
  "Poppins-Light",
  "Poppins-MediumItalic",
  "Poppins-Medium",
  "Poppins-Regular",
  "Poppins-SemiBoldItalic",
  "Poppins-SemiBold",
  "Poppins-ThinItalic",
  "Poppins-Thin",
  "PressStart2P-Regular",
  "Questrial-Regular",
  "Questrian",
  "RacingSansOne-Regular",
  "Ralliankara Personal Use Only",
  "Ralliankara Personal Use Only",
  "Righteous-Regular",
  "Road_Rage",
  "Roblox",
  "RubikMonoOne-Regular",
  "RumRaisin-Regular",
  "SallimSignature",
  "SallimSignature",
  "Schoolbell-Regular",
  "SedgwickAveDisplay-Regular",
  "SedgwickAve-Regular",
  "SFProDisplay-Black",
  "SFProDisplay-Bold",
  "SFProDisplay-Heavy",
  "SFProDisplay-Light",
  "SFProDisplay-Medium",
  "SFProDisplay-Regular",
  "SFProDisplay-Semibold",
  "SFProDisplay-Thin",
  "SFProDisplay-Ultralight",
  "SFProText-Bold",
  "SFProText-Heavy",
  "SFProText-Light",
  "SFProText-Medium",
  "SFProText-Regular",
  "SFProText-Semibold",
  "ShortStack-Regular",
  "Shrikhand-Regular",
  "SigmarOne-Regular",
  "Sillii Willinn Font",
  "SIMPLICITY PERSONALUSE",
  "SIMPLICITY SHADOW PERSONAL USE",
  "Simplicity",
  "Simplicity",
  "Sin_City",
  "sing_14l",
  "Slackey-Regular",
  "soloist1",
  "soloist3d",
  "soloistacad",
  "soloistchrome",
  "soloistcond1",
  "soloistexpand1",
  "soloistextraital1",
  "soloistgrad1",
  "soloisthalf1",
  "soloisthalf21",
  "soloisthalf",
  "soloistital1",
  "soloistlaser1",
  "soloistlaserital1",
  "soloistleft1",
  "soloistout",
  "soloiststraight1",
  "soloisttitle1",
  "soupofjustice",
  "speedwagon3dital",
  "speedwagon3d",
  "speedwagoncondital",
  "speedwagoncond",
  "speedwagonexpandital",
  "speedwagonexpand",
  "speedwagonhalfital",
  "speedwagonhalf",
  "speedwagonital",
  "speedwagonlaserital",
  "speedwagonlaser",
  "speedwagonleft",
  "speedwagonsuperital",
  "speedwagon",
  "speedwagonxtraexpandital",
  "speedwagonxtraexpand",
  "SpicyRice-Regular",
  "Splatch",
  "Squirk",
  "Star Wars",
  "Starborn",
  "Starborn",
  "Stella Demo",
  "Stella Demo",
  "strude",
  "SugarpunchDEMO",
  "Summer Splash Display",
  "Summer Splash",
  "Sunkist Squash",
  "Sunkist Squash",
  "Super Comic",
  "Supercell-magic-webfont",
  "sweet purple",
  "sweet purple",
  "Teko-Bold",
  "Teko-Light",
  "Teko-Medium",
  "Teko-Regular",
  "Teko-SemiBold",
  "The Blacklist",
  "TitanOne-Regular",
  "Toxico",
  "TradeWinds-Regular",
  "Unicorn Pop",
  "Unicorn Pop",
  "usuzi3dital",
  "usuzi3d",
  "usuziboldital",
  "usuzibold",
  "usuzicondital",
  "usuzicond",
  "usuziexpandital",
  "usuziexpand",
  "usuzigradital",
  "usuzigrad",
  "usuzihalfital",
  "usuzihalf",
  "usuziital",
  "usuzileft",
  "usuzisemital",
  "usuzi",
  "VTC-GarageSale",
  "VTC-GarageSaleOutlined",
  "VTC-GarageSale",
  "WalterTurncoat-Regular",
  "WendyOne-Regular",
  "White On Black",
  "Wicked Mouse Demo",
  "ZCOOLKuaiLe-Regular",
];
