import "react-native-gesture-handler";

import { StatusBar } from "expo-status-bar";
import * as SplashScreen from "expo-splash-screen";

//navigation
import { NavigationProvider } from "./src/app/routes";

// redux
import { Provider } from "react-redux";
import store from "./src/app/redux/store";
import { useCallback } from "react";
import { useFonts } from "expo-font";
import { View } from "react-native";


export default function App() {
  const [fontsLoaded, fontError] = useFonts({
    "Abel-Regular": require("./assets/fonts/Abel-Regular.ttf"),
    "Academic M54": require("./assets/fonts/Academic M54.ttf"),
    "Acids!": require("./assets/fonts/Acids!.otf"),
    "Raleway-Light":require("./assets/fonts/Raleway-Light.ttf"),
    "Raleway-Medium":require("./assets/fonts/Raleway-Medium.ttf"),
    "Aileron-BlackItalic": require("./assets/fonts/Aileron-BlackItalic.otf"),
    "Aileron-Black": require("./assets/fonts/Aileron-Black.otf"),
    "Aileron-BoldItalic": require("./assets/fonts/Aileron-BoldItalic.otf"),
    "Aileron-Bold": require("./assets/fonts/Aileron-Bold.otf"),
    "Aileron-HeavyItalic": require("./assets/fonts/Aileron-HeavyItalic.otf"),
    "Aileron-Heavy": require("./assets/fonts/Aileron-Heavy.otf"),
    "Aileron-Italic": require("./assets/fonts/Aileron-Italic.otf"),
    "Aileron-LightItalic": require("./assets/fonts/Aileron-LightItalic.otf"),
    "Aileron-Light": require("./assets/fonts/Aileron-Light.otf"),
    "Aileron-Regular": require("./assets/fonts/Aileron-Regular.otf"),
    "Aileron-SemiBoldItalic": require("./assets/fonts/Aileron-SemiBoldItalic.otf"),
    "Aileron-SemiBold": require("./assets/fonts/Aileron-SemiBold.otf"),
    "Aileron-ThinItalic": require("./assets/fonts/Aileron-ThinItalic.otf"),
    "Aileron-Thin": require("./assets/fonts/Aileron-Thin.otf"),
    "Aileron-UltraLightItalic": require("./assets/fonts/Aileron-UltraLightItalic.otf"),
    "Aileron-UltraLight": require("./assets/fonts/Aileron-UltraLight.otf"),
    "Air Americana": require("./assets/fonts/Air Americana.ttf"),
    "Aladin-Regular": require("./assets/fonts/Aladin-Regular.ttf"),
    "Alegreya-BlackItalic": require("./assets/fonts/Alegreya-BlackItalic.ttf"),
    "Alegreya-Black": require("./assets/fonts/Alegreya-Black.ttf"),
    "Alegreya-BoldItalic": require("./assets/fonts/Alegreya-BoldItalic.ttf"),
    "Alegreya-Bold": require("./assets/fonts/Alegreya-Bold.ttf"),
    "Alegreya-ExtraBoldItalic": require("./assets/fonts/Alegreya-ExtraBoldItalic.ttf"),
    "Alegreya-ExtraBold": require("./assets/fonts/Alegreya-ExtraBold.ttf"),
    "Alegreya-Italic": require("./assets/fonts/Alegreya-Italic.ttf"),
    "Alegreya-MediumItalic": require("./assets/fonts/Alegreya-MediumItalic.ttf"),
    "Alegreya-Medium": require("./assets/fonts/Alegreya-Medium.ttf"),
    "Alegreya-Regular": require("./assets/fonts/Alegreya-Regular.ttf"),
    "AlegreyaSans-BlackItalic": require("./assets/fonts/AlegreyaSans-BlackItalic.ttf"),
    "AlegreyaSans-Black": require("./assets/fonts/AlegreyaSans-Black.ttf"),
    "AlegreyaSans-BoldItalic": require("./assets/fonts/AlegreyaSans-BoldItalic.ttf"),
    "AlegreyaSans-Bold": require("./assets/fonts/AlegreyaSans-Bold.ttf"),
    "AlegreyaSans-ExtraBoldItalic": require("./assets/fonts/AlegreyaSans-ExtraBoldItalic.ttf"),
    "AlegreyaSans-ExtraBold": require("./assets/fonts/AlegreyaSans-ExtraBold.ttf"),
    "AlegreyaSans-Italic": require("./assets/fonts/AlegreyaSans-Italic.ttf"),
    "AlegreyaSans-LightItalic": require("./assets/fonts/AlegreyaSans-LightItalic.ttf"),
    "AlegreyaSans-Light": require("./assets/fonts/AlegreyaSans-Light.ttf"),
    "AlegreyaSans-MediumItalic": require("./assets/fonts/AlegreyaSans-MediumItalic.ttf"),
    "AlegreyaSans-Medium": require("./assets/fonts/AlegreyaSans-Medium.ttf"),
    "AlegreyaSans-Regular": require("./assets/fonts/AlegreyaSans-Regular.ttf"),
    "AlegreyaSans-ThinItalic": require("./assets/fonts/AlegreyaSans-ThinItalic.ttf"),
    "AlegreyaSans-Thin": require("./assets/fonts/AlegreyaSans-Thin.ttf"),
    "AlegreyaSC-BlackItalic": require("./assets/fonts/AlegreyaSC-BlackItalic.ttf"),
    "AlegreyaSC-Black": require("./assets/fonts/AlegreyaSC-Black.ttf"),
    "AlegreyaSC-BoldItalic": require("./assets/fonts/AlegreyaSC-BoldItalic.ttf"),
    "AlegreyaSC-Bold": require("./assets/fonts/AlegreyaSC-Bold.ttf"),
    "AlegreyaSC-ExtraBoldItalic": require("./assets/fonts/AlegreyaSC-ExtraBoldItalic.ttf"),
    "AlegreyaSC-ExtraBold": require("./assets/fonts/AlegreyaSC-ExtraBold.ttf"),
    "AlegreyaSC-Italic": require("./assets/fonts/AlegreyaSC-Italic.ttf"),
    "AlegreyaSC-MediumItalic": require("./assets/fonts/AlegreyaSC-MediumItalic.ttf"),
    "AlegreyaSC-Medium": require("./assets/fonts/AlegreyaSC-Medium.ttf"),
    "AlegreyaSC-Regular": require("./assets/fonts/AlegreyaSC-Regular.ttf"),
    Aliyah: require("./assets/fonts/Aliyah.ttf"),
    "Allan-Bold": require("./assets/fonts/Allan-Bold.ttf"),
    "Allan-Regular": require("./assets/fonts/Allan-Regular.ttf"),
    "Alone On Earth": require("./assets/fonts/Alone On Earth.otf"),
    "Amiko-Bold": require("./assets/fonts/Amiko-Bold.ttf"),
    "Amiko-Regular": require("./assets/fonts/Amiko-Regular.ttf"),
    "Amiko-SemiBold": require("./assets/fonts/Amiko-SemiBold.ttf"),
    "Among us 2": require("./assets/fonts/Among us 2.ttf"),
    "Among us": require("./assets/fonts/Among us.ttf"),
    "Anton-Regular": require("./assets/fonts/Anton-Regular.ttf"),
    "ArchivoBlack-Regular": require("./assets/fonts/ArchivoBlack-Regular.ttf"),
    "ArimaMadurai-Black": require("./assets/fonts/ArimaMadurai-Black.ttf"),
    "ArimaMadurai-Bold": require("./assets/fonts/ArimaMadurai-Bold.ttf"),
    "ArimaMadurai-ExtraBold": require("./assets/fonts/ArimaMadurai-ExtraBold.ttf"),
    "ArimaMadurai-ExtraLight": require("./assets/fonts/ArimaMadurai-ExtraLight.ttf"),
    "ArimaMadurai-Light": require("./assets/fonts/ArimaMadurai-Light.ttf"),
    "ArimaMadurai-Medium": require("./assets/fonts/ArimaMadurai-Medium.ttf"),
    "ArimaMadurai-Regular": require("./assets/fonts/ArimaMadurai-Regular.ttf"),
    "ArimaMadurai-Thin": require("./assets/fonts/ArimaMadurai-Thin.ttf"),
    "Army Buster": require("./assets/fonts/Army Buster.otf"),
    //"Athletic.TTF": require("./assets/fonts/Athletic.TTF"),
    "Averus (DEMO)": require("./assets/fonts/Averus (DEMO).ttf"),
    "Ayudisha-Free-Version": require("./assets/fonts/Ayudisha-Free-Version.ttf"),
    "Baby Monsta Inner": require("./assets/fonts/Baby Monsta Inner.otf"),
    "Baby Monsta Shadow": require("./assets/fonts/Baby Monsta Shadow.otf"),
    "Baby Monsta": require("./assets/fonts/Baby Monsta.otf"),
    "BalooThambi-Regular": require("./assets/fonts/BalooThambi-Regular.ttf"),
    "Bangers-Regular": require("./assets/fonts/Bangers-Regular.ttf"),
    "BebasNeue Bold": require("./assets/fonts/BebasNeue Bold.otf"),
    "BebasNeue Book": require("./assets/fonts/BebasNeue Book.ttf"),
    "BebasNeue Light": require("./assets/fonts/BebasNeue Light.ttf"),
    "BebasNeue Regular": require("./assets/fonts/BebasNeue Regular.ttf"),
    "BebasNeue Thin": require("./assets/fonts/BebasNeue Thin.ttf"),
    BebasNeue: require("./assets/fonts/BebasNeue.otf"),
    BebasTam: require("./assets/fonts/BebasTam.ttf"),
    //"BEBAS_.TTF": require("./assets/fonts/BEBAS_.TTF"),
    Bellasya: require("./assets/fonts/Bellasya.ttf"),
    BillionDreams_PERSONAL: require("./assets/fonts/BillionDreams_PERSONAL.ttf"),
    "BioRhyme-Bold": require("./assets/fonts/BioRhyme-Bold.ttf"),
    "BioRhyme-ExtraBold": require("./assets/fonts/BioRhyme-ExtraBold.ttf"),
    "BioRhyme-ExtraLight": require("./assets/fonts/BioRhyme-ExtraLight.ttf"),
    "BioRhyme-Light": require("./assets/fonts/BioRhyme-Light.ttf"),
    "BioRhyme-Regular": require("./assets/fonts/BioRhyme-Regular.ttf"),
    "BlackOpsOne-Regular": require("./assets/fonts/BlackOpsOne-Regular.ttf"),
    BlackSingature: require("./assets/fonts/BlackSingature.ttf"),
    Blacksword: require("./assets/fonts/Blacksword.otf"),
    "BLINK SHARK": require("./assets/fonts/BLINK SHARK.otf"),
    "Bloomer DEMO": require("./assets/fonts/Bloomer DEMO.otf"),
    Blur: require("./assets/fonts/Blur.ttf"),
    "BowlbyOne-Regular": require("./assets/fonts/BowlbyOne-Regular.ttf"),
    "BowlbyOneSC-Regular": require("./assets/fonts/BowlbyOneSC-Regular.ttf"),
    Bubblegum: require("./assets/fonts/Bubblegum.ttf"),
    "budmo jiggler": require("./assets/fonts/budmo jiggler.ttf"),
    "budmo jigglish": require("./assets/fonts/budmo jigglish.ttf"),
    "Bungee-Regular": require("./assets/fonts/Bungee-Regular.ttf"),
    "BungeeShade-Regular": require("./assets/fonts/BungeeShade-Regular.ttf"),
    "Cabin-BoldItalic": require("./assets/fonts/Cabin-BoldItalic.ttf"),
    "Cabin-Bold": require("./assets/fonts/Cabin-Bold.ttf"),
    "Cabin-Italic": require("./assets/fonts/Cabin-Italic.ttf"),
    "Cabin-MediumItalic": require("./assets/fonts/Cabin-MediumItalic.ttf"),
    "Cabin-Medium": require("./assets/fonts/Cabin-Medium.ttf"),
    "Cabin-Regular": require("./assets/fonts/Cabin-Regular.ttf"),
    "Cabin-SemiBoldItalic": require("./assets/fonts/Cabin-SemiBoldItalic.ttf"),
    "Cabin-SemiBold": require("./assets/fonts/Cabin-SemiBold.ttf"),
    "Cambay-BoldItalic": require("./assets/fonts/Cambay-BoldItalic.ttf"),
    "Cambay-Bold": require("./assets/fonts/Cambay-Bold.ttf"),
    "Cambay-Italic": require("./assets/fonts/Cambay-Italic.ttf"),
    "Cambay-Regular": require("./assets/fonts/Cambay-Regular.ttf"),
    "Candy Beans": require("./assets/fonts/Candy Beans.otf"),
    "Canter-Bold3D": require("./assets/fonts/Canter-Bold3D.otf"),
    "Canter-Bold": require("./assets/fonts/Canter-Bold.otf"),
    "Canter-BoldShadow": require("./assets/fonts/Canter-BoldShadow.otf"),
    "Canter-BoldStrips": require("./assets/fonts/Canter-BoldStrips.otf"),
    "Canter-Light": require("./assets/fonts/Canter-Light.otf"),
    "Canter-Outline": require("./assets/fonts/Canter-Outline.otf"),
    "CarroisGothicSC-Regular": require("./assets/fonts/CarroisGothicSC-Regular.ttf"),
    CarterOne: require("./assets/fonts/CarterOne.ttf"),
    "Cartoon cookies Tilted": require("./assets/fonts/Cartoon cookies Tilted.ttf"),
    "Cartoon cookies": require("./assets/fonts/Cartoon cookies.ttf"),
    cartoonist_kooky: require("./assets/fonts/cartoonist_kooky.ttf"),
    Cartoon: require("./assets/fonts/Cartoon.ttf"),
    "Casino3DFilled-Italic": require("./assets/fonts/Casino3DFilled-Italic.ttf"),
    "Casino3DFilledMarquee-Italic": require("./assets/fonts/Casino3DFilledMarquee-Italic.ttf"),
    Casino3DFilledMarquee: require("./assets/fonts/Casino3DFilledMarquee.ttf"),
    Casino3DFilled: require("./assets/fonts/Casino3DFilled.ttf"),
    "Casino3D-Italic": require("./assets/fonts/Casino3D-Italic.ttf"),
    "Casino3DLines-Italic": require("./assets/fonts/Casino3DLines-Italic.ttf"),
    "Casino3DLinesMarquee-Italic": require("./assets/fonts/Casino3DLinesMarquee-Italic.ttf"),
    Casino3DLinesMarquee: require("./assets/fonts/Casino3DLinesMarquee.ttf"),
    Casino3DLines: require("./assets/fonts/Casino3DLines.ttf"),
    "Casino3DMarquee-Italic": require("./assets/fonts/Casino3DMarquee-Italic.ttf"),
    Casino3DMarquee: require("./assets/fonts/Casino3DMarquee.ttf"),
    Casino3D: require("./assets/fonts/Casino3D.ttf"),
    "CasinoFlat-Italic": require("./assets/fonts/CasinoFlat-Italic.ttf"),
    "CasinoFlatShadow-Italic": require("./assets/fonts/CasinoFlatShadow-Italic.ttf"),
    CasinoFlatShadow: require("./assets/fonts/CasinoFlatShadow.ttf"),
    CasinoFlat: require("./assets/fonts/CasinoFlat.ttf"),
    "Casino-Italic": require("./assets/fonts/Casino-Italic.ttf"),
    "CasinoShadow-Italic": require("./assets/fonts/CasinoShadow-Italic.ttf"),
    CasinoShadow: require("./assets/fonts/CasinoShadow.ttf"),
    Casino: require("./assets/fonts/Casino.ttf"),
    "CevicheOne-Regular": require("./assets/fonts/CevicheOne-Regular.ttf"),
    "Chango-Regular": require("./assets/fonts/Chango-Regular.ttf"),
    "ChelseaMarket-Regular": require("./assets/fonts/ChelseaMarket-Regular.ttf"),
    Chunq: require("./assets/fonts/Chunq.ttf"),
    "Club de la pelea": require("./assets/fonts/Club de la pelea.ttf"),
    "Cocogoose-Compressed-Bold-Italic-trial": require("./assets/fonts/Cocogoose-Compressed-Bold-Italic-trial.ttf"),
    "Cocogoose-Compressed-Bold-trial": require("./assets/fonts/Cocogoose-Compressed-Bold-trial.ttf"),
    "Cocogoose-Compressed-Letterpress-trial": require("./assets/fonts/Cocogoose-Compressed-Letterpress-trial.ttf"),
    "Cocogoose-Compressed-Light-Italic-trial": require("./assets/fonts/Cocogoose-Compressed-Light-Italic-trial.ttf"),
    "Cocogoose-Compressed-Light-Trial": require("./assets/fonts/Cocogoose-Compressed-Light-Trial.ttf"),
    "Cocogoose-Compressed-Regular-italic-trial": require("./assets/fonts/Cocogoose-Compressed-Regular-italic-trial.ttf"),
    "Cocogoose-Compressed-Regular-Trial": require("./assets/fonts/Cocogoose-Compressed-Regular-Trial.ttf"),
    "Cocogoose-Compressed-Semilight-Italic-trial": require("./assets/fonts/Cocogoose-Compressed-Semilight-Italic-trial.ttf"),
    "Cocogoose-Compressed-Semilight-Trial": require("./assets/fonts/Cocogoose-Compressed-Semilight-Trial.ttf"),
    "Cocogoose-Compressed-Thin-Italic-trial": require("./assets/fonts/Cocogoose-Compressed-Thin-Italic-trial.ttf"),
    "Cocogoose-Compressed-Thin-Trial": require("./assets/fonts/Cocogoose-Compressed-Thin-Trial.ttf"),
    "Cocogoose-Compressed-Ultralight-Italic-trial": require("./assets/fonts/Cocogoose-Compressed-Ultralight-Italic-trial.ttf"),
    "Cocogoose-Compressed-UltraLight-Trial": require("./assets/fonts/Cocogoose-Compressed-UltraLight-Trial.ttf"),
    "Cocogoose-Condensed-Letterpress-trial": require("./assets/fonts/Cocogoose-Condensed-Letterpress-trial.ttf"),
    "Cocogoose-Condensed-Light-Italic-trial": require("./assets/fonts/Cocogoose-Condensed-Light-Italic-trial.ttf"),
    "Cocogoose-Condensed-Light-trial": require("./assets/fonts/Cocogoose-Condensed-Light-trial.ttf"),
    "Cocogoose-Condensed-Regular-Italic-trial": require("./assets/fonts/Cocogoose-Condensed-Regular-Italic-trial.ttf"),
    "Cocogoose-Condensed-Regular-trial": require("./assets/fonts/Cocogoose-Condensed-Regular-trial.ttf"),
    "Cocogoose-Condensed-Semilight-Italic-trial": require("./assets/fonts/Cocogoose-Condensed-Semilight-Italic-trial.ttf"),
    "Cocogoose-Condensed-Semilight-trial": require("./assets/fonts/Cocogoose-Condensed-Semilight-trial.ttf"),
    "Cocogoose-Condensed-Thin-Italic-trial": require("./assets/fonts/Cocogoose-Condensed-Thin-Italic-trial.ttf"),
    "Cocogoose-Condensed-Thin-trial": require("./assets/fonts/Cocogoose-Condensed-Thin-trial.ttf"),
    "Cocogoose-Condensed-Ultralight-Italic-trial": require("./assets/fonts/Cocogoose-Condensed-Ultralight-Italic-trial.ttf"),
    "Cocogoose-Condensed-Ultralight-trial": require("./assets/fonts/Cocogoose-Condensed-Ultralight-trial.ttf"),
    "Cocogoose-Narrow-Letterpress-trial": require("./assets/fonts/Cocogoose-Narrow-Letterpress-trial.ttf"),
    "Cocogoose-Narrow-Light-Italic-trial": require("./assets/fonts/Cocogoose-Narrow-Light-Italic-trial.ttf"),
    "Cocogoose-Narrow-Light-trial": require("./assets/fonts/Cocogoose-Narrow-Light-trial.ttf"),
    "Cocogoose-Narrow-Regular-Italic-trial": require("./assets/fonts/Cocogoose-Narrow-Regular-Italic-trial.ttf"),
    "Cocogoose-Narrow-Regular-trial": require("./assets/fonts/Cocogoose-Narrow-Regular-trial.ttf"),
    "Cocogoose-Narrow-Semilight-Italic-trial": require("./assets/fonts/Cocogoose-Narrow-Semilight-Italic-trial.ttf"),
    "Cocogoose-Narrow-Semilight-trial": require("./assets/fonts/Cocogoose-Narrow-Semilight-trial.ttf"),
    "Cocogoose-Narrow-Thin-Italic-trial": require("./assets/fonts/Cocogoose-Narrow-Thin-Italic-trial.ttf"),
    "Cocogoose-Narrow-Thin-trial": require("./assets/fonts/Cocogoose-Narrow-Thin-trial.ttf"),
    "Cocogoose-Narrow-Ultralight-Italic-trial": require("./assets/fonts/Cocogoose-Narrow-Ultralight-Italic-trial.ttf"),
    "Cocogoose-Narrow-Ultralight-trial": require("./assets/fonts/Cocogoose-Narrow-Ultralight-trial.ttf"),
    "Coconut Cookies": require("./assets/fonts/Coconut Cookies.ttf"),
    COD: require("./assets/fonts/COD.otf"),
    "Comic Kings": require("./assets/fonts/Comic Kings.ttf"),
    //"Comic.TTF": require("./assets/fonts/Comic.TTF"),
    "ComingSoon-Regular": require("./assets/fonts/ComingSoon-Regular.ttf"),
    "Comix Loud": require("./assets/fonts/Comix Loud.ttf"),
    "Cormorant-BoldItalic": require("./assets/fonts/Cormorant-BoldItalic.ttf"),
    "Cormorant-Bold": require("./assets/fonts/Cormorant-Bold.ttf"),
    "CormorantGaramond-BoldItalic": require("./assets/fonts/CormorantGaramond-BoldItalic.ttf"),
    "CormorantGaramond-Bold": require("./assets/fonts/CormorantGaramond-Bold.ttf"),
    "CormorantGaramond-Italic": require("./assets/fonts/CormorantGaramond-Italic.ttf"),
    "CormorantGaramond-LightItalic": require("./assets/fonts/CormorantGaramond-LightItalic.ttf"),
    "CormorantGaramond-Light": require("./assets/fonts/CormorantGaramond-Light.ttf"),
    "CormorantGaramond-MediumItalic": require("./assets/fonts/CormorantGaramond-MediumItalic.ttf"),
    "CormorantGaramond-Medium": require("./assets/fonts/CormorantGaramond-Medium.ttf"),
    "CormorantGaramond-Regular": require("./assets/fonts/CormorantGaramond-Regular.ttf"),
    "CormorantGaramond-SemiBoldItalic": require("./assets/fonts/CormorantGaramond-SemiBoldItalic.ttf"),
    "CormorantGaramond-SemiBold": require("./assets/fonts/CormorantGaramond-SemiBold.ttf"),
    "Cormorant-Italic": require("./assets/fonts/Cormorant-Italic.ttf"),
    "Cormorant-LightItalic": require("./assets/fonts/Cormorant-LightItalic.ttf"),
    "Cormorant-Light": require("./assets/fonts/Cormorant-Light.ttf"),
    "Cormorant-MediumItalic": require("./assets/fonts/Cormorant-MediumItalic.ttf"),
    "Cormorant-Medium": require("./assets/fonts/Cormorant-Medium.ttf"),
    "Cormorant-Regular": require("./assets/fonts/Cormorant-Regular.ttf"),
    "Cormorant-SemiBoldItalic": require("./assets/fonts/Cormorant-SemiBoldItalic.ttf"),
    "Cormorant-SemiBold": require("./assets/fonts/Cormorant-SemiBold.ttf"),
    CoveredByYourGrace: require("./assets/fonts/CoveredByYourGrace.ttf"),
    "Creepster-Regular": require("./assets/fonts/Creepster-Regular.ttf"),
    "Demode-Negative": require("./assets/fonts/Demode-Negative.ttf"),
    Demode: require("./assets/fonts/Demode.ttf"),
    "DenkOne-Regular": require("./assets/fonts/DenkOne-Regular.ttf"),
    "Dimbo Italic": require("./assets/fonts/Dimbo Italic.ttf"),
    "Dimbo Regular": require("./assets/fonts/Dimbo Regular.ttf"),
    //"DIMIS___.TTF": require("./assets/fonts/DIMIS___.TTF"),
    //"DIMITRI_.TTF": require("./assets/fonts/DIMITRI_.TTF"),
    "Distorsion 2": require("./assets/fonts/Distorsion 2.otf"),
    Distorsión: require("./assets/fonts/Distorsión.ttf"),
    "Dokdo-Regular": require("./assets/fonts/Dokdo-Regular.ttf"),
    "Dot Spot": require("./assets/fonts/Dot Spot.ttf"),
    "Drifttype Solid": require("./assets/fonts/Drifttype Solid.ttf"),
    Drifttype: require("./assets/fonts/Drifttype.ttf"),
    "Eighties FREE": require("./assets/fonts/Eighties FREE.ttf"),
    "EmilysCandy-Regular": require("./assets/fonts/EmilysCandy-Regular.ttf"),
    "EricaOne-Regular": require("./assets/fonts/EricaOne-Regular.ttf"),
    "Ewert-Regular": require("./assets/fonts/Ewert-Regular.ttf"),
    ExtraBlur: require("./assets/fonts/ExtraBlur.ttf"),
    /*     "f02.TTF": require("./assets/fonts/f02.TTF"),
    "f06.TTF": require("./assets/fonts/f06.TTF"),
    "f08.TTF": require("./assets/fonts/f08.TTF"),
    "f10.TTF": require("./assets/fonts/f10.TTF"),
    "f23.TTF": require("./assets/fonts/f23.TTF"),
    "f38.TTF": require("./assets/fonts/f38.TTF"),
    "f39.TTF": require("./assets/fonts/f39.TTF"),
    "f43.TTF": require("./assets/fonts/f43.TTF"),
    "f5.TTF": require("./assets/fonts/f5.TTF"), */
    "FALL GUYS": require("./assets/fonts/FALL GUYS.ttf"),
    "Farsan-Regular": require("./assets/fonts/Farsan-Regular.ttf"),
    "FasterOne-Regular": require("./assets/fonts/FasterOne-Regular.ttf"),
    /*     "FE11003T.TTF": require("./assets/fonts/FE11003T.TTF"),
    "FE11004T.TTF": require("./assets/fonts/FE11004T.TTF"),
    "FE11006T.TTF": require("./assets/fonts/FE11006T.TTF"),
    "FE11042T.TTF": require("./assets/fonts/FE11042T.TTF"),
    "FE11044T.TTF": require("./assets/fonts/FE11044T.TTF"),
    "FE11046T.TTF": require("./assets/fonts/FE11046T.TTF"), */
    "Feral-Regular": require("./assets/fonts/Feral-Regular.ttf"),
    "FontdinerSwanky-Regular": require("./assets/fonts/FontdinerSwanky-Regular.ttf"),
    Fortnite: require("./assets/fonts/Fortnite.ttf"),
    FranchiseFilled: require("./assets/fonts/FranchiseFilled.ttf"),
    Franchise: require("./assets/fonts/Franchise.ttf"),
    "FrancoisOne-Regular": require("./assets/fonts/FrancoisOne-Regular.ttf"),
    "FreckleFace-Regular": require("./assets/fonts/FreckleFace-Regular.ttf"),
    "FredokaOne-Regular": require("./assets/fonts/FredokaOne-Regular.ttf"),
    "Free fire": require("./assets/fonts/Free fire.otf"),
    "Fresca-Regular": require("./assets/fonts/Fresca-Regular.ttf"),
    "Fruktur-Regular": require("./assets/fonts/Fruktur-Regular.ttf"),
    // "FUTRFW.TTF": require("./assets/fonts/FUTRFW.TTF"),
    FutuBdIt: require("./assets/fonts/FutuBdIt.ttf"),
    FutuBd__: require("./assets/fonts/FutuBd__.ttf"),
    FutuBkIt: require("./assets/fonts/FutuBkIt.ttf"),
    FutuBk__: require("./assets/fonts/FutuBk__.ttf"),
    FutuHvIt: require("./assets/fonts/FutuHvIt.ttf"),
    FutuHv__: require("./assets/fonts/FutuHv__.ttf"),
    FutuLtIt: require("./assets/fonts/FutuLtIt.ttf"),
    FutuLt__: require("./assets/fonts/FutuLt__.ttf"),
    FutuMdIt: require("./assets/fonts/FutuMdIt.ttf"),
    FutuMd__: require("./assets/fonts/FutuMd__.ttf"),
    // "Futura  Book.TTF": require("./assets/fonts/Futura  Book.TTF"),
    /*  "Futura 2 Ital.TTF": require("./assets/fonts/Futura 2 Ital.TTF"),
    "Futura 2 Normal.TTF": require("./assets/fonts/Futura 2 Normal.TTF"), */
    "Futura Black BT": require("./assets/fonts/Futura Black BT.ttf"),
    "Futura Bold BT": require("./assets/fonts/Futura Bold BT.ttf"),
    "Futura Bold Italic BT": require("./assets/fonts/Futura Bold Italic BT.ttf"),
    /* "Futura Bold Obl.TTF": require("./assets/fonts/Futura Bold Obl.TTF"),
    "Futura Bold.TTF": require("./assets/fonts/Futura Bold.TTF"),
    "Futura Cnd Bold Ital.TTF": require("./assets/fonts/Futura Cnd Bold Ital.TTF"),
    "Futura Cnd Bold.TTF": require("./assets/fonts/Futura Cnd Bold.TTF"),
    "Futura Cnd Extra Bold Thin.TTF": require("./assets/fonts/Futura Cnd Extra Bold Thin.TTF"),
    "Futura Cnd Ital.TTF": require("./assets/fonts/Futura Cnd Ital.TTF"),
    "Futura Cnd Norma.TTF": require("./assets/fonts/Futura Cnd Norma.TTF"),
    "Futura Cnd Obl Bo.TTF": require("./assets/fonts/Futura Cnd Obl Bo.TTF"),
    "Futura Cnd Obl No.TTF": require("./assets/fonts/Futura Cnd Obl No.TTF"), */
    /* "Futura Ext Obl Bold.TTF": require("./assets/fonts/Futura Ext Obl Bold.TTF"),
    "Futura Ext Obl No.TTF": require("./assets/fonts/Futura Ext Obl No.TTF"), */
    "Futura Extra Black BT": require("./assets/fonts/Futura Extra Black BT.ttf"),
    "Futura Light BT": require("./assets/fonts/Futura Light BT.ttf"),
    "Futura Light Italic BT": require("./assets/fonts/Futura Light Italic BT.ttf"),
    /*   "Futura Normal.TTF": require("./assets/fonts/Futura Normal.TTF"),
    "Futura Obl Bold.TTF": require("./assets/fonts/Futura Obl Bold.TTF"),
    "Futura Obl Normal.TTF": require("./assets/fonts/Futura Obl Normal.TTF"),
    "Futura Poster Light.TTF": require("./assets/fonts/Futura Poster Light.TTF"),
    "Futura Thin.TTF": require("./assets/fonts/Futura Thin.TTF"), */
    Futurabc: require("./assets/fonts/Futurabc.ttf"),
    Futurahi: require("./assets/fonts/Futurahi.ttf"),
    Futurah: require("./assets/fonts/Futurah.ttf"),
    Futuralc: require("./assets/fonts/Futuralc.ttf"),
    Futuramc: require("./assets/fonts/Futuramc.ttf"),
    Futurami: require("./assets/fonts/Futurami.ttf"),
    Futuram: require("./assets/fonts/Futuram.ttf"),
    Futurani: require("./assets/fonts/Futurani.ttf"),
    Futuran: require("./assets/fonts/Futuran.ttf"),
    Futura: require("./assets/fonts/Futura.ttf"),
    Futurbci: require("./assets/fonts/Futurbci.ttf"),
    "Future Sallow Wide": require("./assets/fonts/Future Sallow Wide.ttf"),
    "Future Sallow": require("./assets/fonts/Future Sallow.ttf"),
    Futured: require("./assets/fonts/Futured.ttf"),
    FUTURE: require("./assets/fonts/FUTURE.ttf"),
    "Futurex Apocalypse": require("./assets/fonts/Futurex Apocalypse.ttf"),
    "Futurex Phat Italic": require("./assets/fonts/Futurex Phat Italic.ttf"),
    "Futurex Phat Outline Italic": require("./assets/fonts/Futurex Phat Outline Italic.ttf"),
    "Futurex Phat Outline": require("./assets/fonts/Futurex Phat Outline.ttf"),
    "Futurex Phat": require("./assets/fonts/Futurex Phat.ttf"),
    "Futurex Voyager": require("./assets/fonts/Futurex Voyager.ttf"),
    FuturexBob: require("./assets/fonts/FuturexBob.ttf"),
    Futurism: require("./assets/fonts/Futurism.ttf"),
    "Futurist ExtraHeavy Regular": require("./assets/fonts/Futurist ExtraHeavy Regular.ttf"),
    "FuturistBlack Regular": require("./assets/fonts/FuturistBlack Regular.ttf"),
    "FuturistExtraHeavy Italic": require("./assets/fonts/FuturistExtraHeavy Italic.ttf"),
    "Futurist-Stencil Regular": require("./assets/fonts/Futurist-Stencil Regular.ttf"),
    Futurlci: require("./assets/fonts/Futurlci.ttf"),
    Futurmci: require("./assets/fonts/Futurmci.ttf"),
    Futurxkc: require("./assets/fonts/Futurxkc.ttf"),
    Futurxki: require("./assets/fonts/Futurxki.ttf"),
    Futuxkci: require("./assets/fonts/Futuxkci.ttf"),
    Gameplay: require("./assets/fonts/Gameplay.ttf"),
    GIN_AND_SODA_PERSONAL_USE: require("./assets/fonts/GIN_AND_SODA_PERSONAL_USE.ttf"),
    "Glamor-BoldCondensedItalic": require("./assets/fonts/Glamor-BoldCondensedItalic.otf"),
    "Glamor-BoldCondensed": require("./assets/fonts/Glamor-BoldCondensed.otf"),
    "Glamor-BoldExtendedItalic": require("./assets/fonts/Glamor-BoldExtendedItalic.otf"),
    "Glamor-BoldExtended": require("./assets/fonts/Glamor-BoldExtended.otf"),
    "Glamor-BoldItalic": require("./assets/fonts/Glamor-BoldItalic.otf"),
    "Glamor-Bold": require("./assets/fonts/Glamor-Bold.otf"),
    "Glamor-CondensedItalic": require("./assets/fonts/Glamor-CondensedItalic.otf"),
    "Glamor-Condensed": require("./assets/fonts/Glamor-Condensed.otf"),
    "Glamor-ExtendedItalic": require("./assets/fonts/Glamor-ExtendedItalic.otf"),
    "Glamor-Extended": require("./assets/fonts/Glamor-Extended.otf"),
    "Glamor-Italic": require("./assets/fonts/Glamor-Italic.otf"),
    "Glamor-LightCondensedItalic": require("./assets/fonts/Glamor-LightCondensedItalic.otf"),
    "Glamor-LightCondensed": require("./assets/fonts/Glamor-LightCondensed.otf"),
    "Glamor-LightExtendedItalic": require("./assets/fonts/Glamor-LightExtendedItalic.otf"),
    "Glamor-LightExtended": require("./assets/fonts/Glamor-LightExtended.otf"),
    "Glamor-LightItalic": require("./assets/fonts/Glamor-LightItalic.otf"),
    "Glamor-Light": require("./assets/fonts/Glamor-Light.otf"),
    "Glamor-MediumCondensedItali": require("./assets/fonts/Glamor-MediumCondensedItali.otf"),
    "Glamor-MediumCondensed": require("./assets/fonts/Glamor-MediumCondensed.otf"),
    "Glamor-MediumExtendedItalic": require("./assets/fonts/Glamor-MediumExtendedItalic.otf"),
    "Glamor-MediumExtended": require("./assets/fonts/Glamor-MediumExtended.otf"),
    "Glamor-MediumItalic": require("./assets/fonts/Glamor-MediumItalic.otf"),
    "Glamor-Medium": require("./assets/fonts/Glamor-Medium.otf"),
    "Glamor-Regular": require("./assets/fonts/Glamor-Regular.otf"),
    "Glitch 2": require("./assets/fonts/Glitch 2.otf"),
    Glitch: require("./assets/fonts/Glitch.ttf"),
    "GochiHand-Regular": require("./assets/fonts/GochiHand-Regular.ttf"),
    Godzilla: require("./assets/fonts/Godzilla.ttf"),
    GravitasOne: require("./assets/fonts/GravitasOne.ttf"),
    GROBOLD: require("./assets/fonts/GROBOLD.ttf"),
    Grounge: require("./assets/fonts/Grounge.ttf"),
    // "GTA.TTF": require("./assets/fonts/GTA.TTF"),
    "Hallo sans black": require("./assets/fonts/Hallo sans black.otf"),
    "Hallo sans light": require("./assets/fonts/Hallo sans light.otf"),
    "Hallo sans": require("./assets/fonts/Hallo sans.otf"),
    Halo: require("./assets/fonts/Halo.ttf"),
    hansolov3_3dital: require("./assets/fonts/hansolov3_3dital.ttf"),
    hansolov3_3d: require("./assets/fonts/hansolov3_3d.ttf"),
    hansolov3acadital: require("./assets/fonts/hansolov3acadital.ttf"),
    hansolov3acad: require("./assets/fonts/hansolov3acad.ttf"),
    hansolov3condital: require("./assets/fonts/hansolov3condital.ttf"),
    hansolov3cond: require("./assets/fonts/hansolov3cond.ttf"),
    hansolov3expandital: require("./assets/fonts/hansolov3expandital.ttf"),
    hansolov3expand: require("./assets/fonts/hansolov3expand.ttf"),
    hansolov3gradital: require("./assets/fonts/hansolov3gradital.ttf"),
    hansolov3grad: require("./assets/fonts/hansolov3grad.ttf"),
    hansolov3halfital: require("./assets/fonts/hansolov3halfital.ttf"),
    hansolov3half: require("./assets/fonts/hansolov3half.ttf"),
    hansolov3ital: require("./assets/fonts/hansolov3ital.ttf"),
    hansolov3laserital: require("./assets/fonts/hansolov3laserital.ttf"),
    hansolov3laser: require("./assets/fonts/hansolov3laser.ttf"),
    hansolov3left: require("./assets/fonts/hansolov3left.ttf"),
    hansolov3outital: require("./assets/fonts/hansolov3outital.ttf"),
    hansolov3out: require("./assets/fonts/hansolov3out.ttf"),
    hansolov3overital: require("./assets/fonts/hansolov3overital.ttf"),
    hansolov3over: require("./assets/fonts/hansolov3over.ttf"),
    hansolov3platital: require("./assets/fonts/hansolov3platital.ttf"),
    hansolov3plat: require("./assets/fonts/hansolov3plat.ttf"),
    hansolov3: require("./assets/fonts/hansolov3.ttf"),
    "Hello Sunshine": require("./assets/fonts/Hello Sunshine.ttf"),
    "IBMPlexMono-BoldItalic": require("./assets/fonts/IBMPlexMono-BoldItalic.ttf"),
    "IBMPlexMono-Bold": require("./assets/fonts/IBMPlexMono-Bold.ttf"),
    "IBMPlexMono-ExtraLightItalic": require("./assets/fonts/IBMPlexMono-ExtraLightItalic.ttf"),
    "IBMPlexMono-ExtraLight": require("./assets/fonts/IBMPlexMono-ExtraLight.ttf"),
    "IBMPlexMono-Italic": require("./assets/fonts/IBMPlexMono-Italic.ttf"),
    "IBMPlexMono-LightItalic": require("./assets/fonts/IBMPlexMono-LightItalic.ttf"),
    "IBMPlexMono-Light": require("./assets/fonts/IBMPlexMono-Light.ttf"),
    "IBMPlexMono-MediumItalic": require("./assets/fonts/IBMPlexMono-MediumItalic.ttf"),
    "IBMPlexMono-Medium": require("./assets/fonts/IBMPlexMono-Medium.ttf"),
    "IBMPlexMono-Regular": require("./assets/fonts/IBMPlexMono-Regular.ttf"),
    "IBMPlexMono-SemiBoldItalic": require("./assets/fonts/IBMPlexMono-SemiBoldItalic.ttf"),
    "IBMPlexMono-SemiBold": require("./assets/fonts/IBMPlexMono-SemiBold.ttf"),
    "IBMPlexMono-ThinItalic": require("./assets/fonts/IBMPlexMono-ThinItalic.ttf"),
    "IBMPlexMono-Thin": require("./assets/fonts/IBMPlexMono-Thin.ttf"),
    "JosefinSans-BoldItalic": require("./assets/fonts/JosefinSans-BoldItalic.ttf"),
    "JosefinSans-Bold": require("./assets/fonts/JosefinSans-Bold.ttf"),
    "JosefinSans-Italic": require("./assets/fonts/JosefinSans-Italic.ttf"),
    "JosefinSans-LightItalic": require("./assets/fonts/JosefinSans-LightItalic.ttf"),
    "JosefinSans-Light": require("./assets/fonts/JosefinSans-Light.ttf"),
    "JosefinSans-Regular": require("./assets/fonts/JosefinSans-Regular.ttf"),
    "JosefinSans-SemiBoldItalic": require("./assets/fonts/JosefinSans-SemiBoldItalic.ttf"),
    "JosefinSans-SemiBold": require("./assets/fonts/JosefinSans-SemiBold.ttf"),
    "JosefinSans-ThinItalic": require("./assets/fonts/JosefinSans-ThinItalic.ttf"),
    "JosefinSans-Thin": require("./assets/fonts/JosefinSans-Thin.ttf"),
    "Jua-Regular": require("./assets/fonts/Jua-Regular.ttf"),
    "Jungle Land": require("./assets/fonts/Jungle Land.ttf"),
    "Jurassic park": require("./assets/fonts/Jurassic park.ttf"),
    "JustAnotherHand-Regular": require("./assets/fonts/JustAnotherHand-Regular.ttf"),
    "K2D-BoldItalic": require("./assets/fonts/K2D-BoldItalic.ttf"),
    "K2D-Bold": require("./assets/fonts/K2D-Bold.ttf"),
    "K2D-ExtraBoldItalic": require("./assets/fonts/K2D-ExtraBoldItalic.ttf"),
    "K2D-ExtraBold": require("./assets/fonts/K2D-ExtraBold.ttf"),
    "K2D-ExtraLightItalic": require("./assets/fonts/K2D-ExtraLightItalic.ttf"),
    "K2D-ExtraLight": require("./assets/fonts/K2D-ExtraLight.ttf"),
    "K2D-Italic": require("./assets/fonts/K2D-Italic.ttf"),
    "K2D-LightItalic": require("./assets/fonts/K2D-LightItalic.ttf"),
    "K2D-Light": require("./assets/fonts/K2D-Light.ttf"),
    "K2D-MediumItalic": require("./assets/fonts/K2D-MediumItalic.ttf"),
    "K2D-Medium": require("./assets/fonts/K2D-Medium.ttf"),
    "K2D-Regular": require("./assets/fonts/K2D-Regular.ttf"),
    "K2D-SemiBoldItalic": require("./assets/fonts/K2D-SemiBoldItalic.ttf"),
    "K2D-SemiBold": require("./assets/fonts/K2D-SemiBold.ttf"),
    "K2D-ThinItalic": require("./assets/fonts/K2D-ThinItalic.ttf"),
    "K2D-Thin": require("./assets/fonts/K2D-Thin.ttf"),
    "Ka Blam Under": require("./assets/fonts/Ka Blam Under.ttf"),
    "Ka Blam": require("./assets/fonts/Ka Blam.ttf"),
    "Kanit-BlackItalic": require("./assets/fonts/Kanit-BlackItalic.ttf"),
    "Kanit-Black": require("./assets/fonts/Kanit-Black.ttf"),
    "Kanit-BoldItalic": require("./assets/fonts/Kanit-BoldItalic.ttf"),
    "Kanit-Bold": require("./assets/fonts/Kanit-Bold.ttf"),
    "Kanit-ExtraBoldItalic": require("./assets/fonts/Kanit-ExtraBoldItalic.ttf"),
    "Kanit-ExtraBold": require("./assets/fonts/Kanit-ExtraBold.ttf"),
    "Kanit-ExtraLightItalic": require("./assets/fonts/Kanit-ExtraLightItalic.ttf"),
    "Kanit-ExtraLight": require("./assets/fonts/Kanit-ExtraLight.ttf"),
    "Kanit-Italic": require("./assets/fonts/Kanit-Italic.ttf"),
    "Kanit-LightItalic": require("./assets/fonts/Kanit-LightItalic.ttf"),
    "Kanit-Light": require("./assets/fonts/Kanit-Light.ttf"),
    "Kanit-MediumItalic": require("./assets/fonts/Kanit-MediumItalic.ttf"),
    "Kanit-Medium": require("./assets/fonts/Kanit-Medium.ttf"),
    "Kanit-Regular": require("./assets/fonts/Kanit-Regular.ttf"),
    "Kanit-SemiBoldItalic": require("./assets/fonts/Kanit-SemiBoldItalic.ttf"),
    "Kanit-SemiBold": require("./assets/fonts/Kanit-SemiBold.ttf"),
    "Kanit-ThinItalic": require("./assets/fonts/Kanit-ThinItalic.ttf"),
    "Kanit-Thin": require("./assets/fonts/Kanit-Thin.ttf"),
    "Kavoon-Regular": require("./assets/fonts/Kavoon-Regular.ttf"),
    "Knewave-Regular": require("./assets/fonts/Knewave-Regular.ttf"),
    "LondrinaSolid-Black": require("./assets/fonts/LondrinaSolid-Black.ttf"),
    "LondrinaSolid-Light": require("./assets/fonts/LondrinaSolid-Light.ttf"),
    "LondrinaSolid-Regular": require("./assets/fonts/LondrinaSolid-Regular.ttf"),
    "LondrinaSolid-Thin": require("./assets/fonts/LondrinaSolid-Thin.ttf"),
    "Lora-BoldItalic": require("./assets/fonts/Lora-BoldItalic.ttf"),
    "Lora-Bold": require("./assets/fonts/Lora-Bold.ttf"),
    "Lora-Italic": require("./assets/fonts/Lora-Italic.ttf"),
    "Lora-Regular": require("./assets/fonts/Lora-Regular.ttf"),
    "LuckiestGuy-Regular": require("./assets/fonts/LuckiestGuy-Regular.ttf"),
    "Magic Dreams": require("./assets/fonts/Magic Dreams.ttf"),
    "MeriendaOne-Regular": require("./assets/fonts/MeriendaOne-Regular.ttf"),
    Michroma: require("./assets/fonts/Michroma.ttf"),
    "Minecraft-Bold": require("./assets/fonts/Minecraft-Bold.otf"),
    "Modak-Regular": require("./assets/fonts/Modak-Regular.ttf"),
    MUSICNET: require("./assets/fonts/MUSICNET.ttf"),
    "NanumBrushScript-Regular": require("./assets/fonts/NanumBrushScript-Regular.ttf"),
    Naruto: require("./assets/fonts/Naruto.ttf"),
    "Nature Beauty Personal Use": require("./assets/fonts/Nature Beauty Personal Use.ttf"),
    "Neon 3d": require("./assets/fonts/Neon 3d.ttf"),
    Neon: require("./assets/fonts/Neon.ttf"),
    "NexaRustExtras-Free": require("./assets/fonts/NexaRustExtras-Free.otf"),
    "NexaRustHandmade-Extended": require("./assets/fonts/NexaRustHandmade-Extended.otf"),
    "NexaRustSans-Black": require("./assets/fonts/NexaRustSans-Black.otf"),
    "NexaRustScriptL-0": require("./assets/fonts/NexaRustScriptL-0.otf"),
    "NexaRustSlab-BlackShadow01": require("./assets/fonts/NexaRustSlab-BlackShadow01.otf"),
    norwester: require("./assets/fonts/norwester.otf"),
    "Nunito-BlackItalic": require("./assets/fonts/Nunito-BlackItalic.ttf"),
    "Nunito-Black": require("./assets/fonts/Nunito-Black.ttf"),
    "Nunito-BoldItalic": require("./assets/fonts/Nunito-BoldItalic.ttf"),
    "Nunito-Bold": require("./assets/fonts/Nunito-Bold.ttf"),
    "Nunito-ExtraBoldItalic": require("./assets/fonts/Nunito-ExtraBoldItalic.ttf"),
    "Nunito-ExtraBold": require("./assets/fonts/Nunito-ExtraBold.ttf"),
    "Nunito-ExtraLightItalic": require("./assets/fonts/Nunito-ExtraLightItalic.ttf"),
    "Nunito-ExtraLight": require("./assets/fonts/Nunito-ExtraLight.ttf"),
    "Nunito-Italic": require("./assets/fonts/Nunito-Italic.ttf"),
    "Nunito-LightItalic": require("./assets/fonts/Nunito-LightItalic.ttf"),
    "Nunito-Light": require("./assets/fonts/Nunito-Light.ttf"),
    "Nunito-Regular": require("./assets/fonts/Nunito-Regular.ttf"),
    "Nunito-SemiBoldItalic": require("./assets/fonts/Nunito-SemiBoldItalic.ttf"),
    "Nunito-SemiBold": require("./assets/fonts/Nunito-SemiBold.ttf"),
    "Old school": require("./assets/fonts/Old school.ttf"),
    "Oswald-Bold": require("./assets/fonts/Oswald-Bold.ttf"),
    "Oswald-ExtraLight": require("./assets/fonts/Oswald-ExtraLight.ttf"),
    "Oswald-Light": require("./assets/fonts/Oswald-Light.ttf"),
    "Oswald-Medium": require("./assets/fonts/Oswald-Medium.ttf"),
    "Oswald-Regular": require("./assets/fonts/Oswald-Regular.ttf"),
    "Oswald-SemiBold": require("./assets/fonts/Oswald-SemiBold.ttf"),
    "Outrun future Bold Italic": require("./assets/fonts/Outrun future Bold Italic.otf"),
    "Outrun future Bold": require("./assets/fonts/Outrun future Bold.otf"),
    "Outrun future": require("./assets/fonts/Outrun future.otf"),
    "PassionOne-Black": require("./assets/fonts/PassionOne-Black.ttf"),
    "PassionOne-Bold": require("./assets/fonts/PassionOne-Bold.ttf"),
    "PassionOne-Regular": require("./assets/fonts/PassionOne-Regular.ttf"),
    "PermanentMarker-Regular": require("./assets/fonts/PermanentMarker-Regular.ttf"),
    Pincel: require("./assets/fonts/Pincel.ttf"),
    "Planet Of The Apes": require("./assets/fonts/Planet Of The Apes.ttf"),
    "Poppins-BlackItalic": require("./assets/fonts/Poppins-BlackItalic.ttf"),
    "Poppins-Black": require("./assets/fonts/Poppins-Black.ttf"),
    "Poppins-BoldItalic": require("./assets/fonts/Poppins-BoldItalic.ttf"),
    "Poppins-Bold": require("./assets/fonts/Poppins-Bold.ttf"),
    "Poppins-ExtraBoldItalic": require("./assets/fonts/Poppins-ExtraBoldItalic.ttf"),
    "Poppins-ExtraBold": require("./assets/fonts/Poppins-ExtraBold.ttf"),
    "Poppins-ExtraLightItalic": require("./assets/fonts/Poppins-ExtraLightItalic.ttf"),
    "Poppins-ExtraLight": require("./assets/fonts/Poppins-ExtraLight.ttf"),
    "Poppins-Italic": require("./assets/fonts/Poppins-Italic.ttf"),
    "Poppins-LightItalic": require("./assets/fonts/Poppins-LightItalic.ttf"),
    "Poppins-Light": require("./assets/fonts/Poppins-Light.ttf"),
    "Poppins-MediumItalic": require("./assets/fonts/Poppins-MediumItalic.ttf"),
    "Poppins-Medium": require("./assets/fonts/Poppins-Medium.ttf"),
    "Poppins-Regular": require("./assets/fonts/Poppins-Regular.ttf"),
    "Poppins-SemiBoldItalic": require("./assets/fonts/Poppins-SemiBoldItalic.ttf"),
    "Poppins-SemiBold": require("./assets/fonts/Poppins-SemiBold.ttf"),
    "Poppins-ThinItalic": require("./assets/fonts/Poppins-ThinItalic.ttf"),
    "Poppins-Thin": require("./assets/fonts/Poppins-Thin.ttf"),
    "PressStart2P-Regular": require("./assets/fonts/PressStart2P-Regular.ttf"),
    "Questrial-Regular": require("./assets/fonts/Questrial-Regular.ttf"),
    Questrian: require("./assets/fonts/Questrian.otf"),
    "RacingSansOne-Regular": require("./assets/fonts/RacingSansOne-Regular.ttf"),
    "Ralliankara Personal Use Only": require("./assets/fonts/Ralliankara Personal Use Only.ttf"),
    "Righteous-Regular": require("./assets/fonts/Righteous-Regular.ttf"),
    Road_Rage: require("./assets/fonts/Road_Rage.otf"),
    Roblox: require("./assets/fonts/Roblox.ttf"),
    "RubikMonoOne-Regular": require("./assets/fonts/RubikMonoOne-Regular.ttf"),
    "RumRaisin-Regular": require("./assets/fonts/RumRaisin-Regular.ttf"),
    SallimSignature: require("./assets/fonts/SallimSignature.ttf"),
    "Schoolbell-Regular": require("./assets/fonts/Schoolbell-Regular.ttf"),
    "SedgwickAveDisplay-Regular": require("./assets/fonts/SedgwickAveDisplay-Regular.ttf"),
    "SedgwickAve-Regular": require("./assets/fonts/SedgwickAve-Regular.ttf"),
    // "SEGA.TTF": require("./assets/fonts/SEGA.TTF"),
    "SFProDisplay-Black": require("./assets/fonts/SFProDisplay-Black.ttf"),
    "SFProDisplay-Bold": require("./assets/fonts/SFProDisplay-Bold.ttf"),
    "SFProDisplay-Heavy": require("./assets/fonts/SFProDisplay-Heavy.ttf"),
    "SFProDisplay-Light": require("./assets/fonts/SFProDisplay-Light.ttf"),
    "SFProDisplay-Medium": require("./assets/fonts/SFProDisplay-Medium.ttf"),
    "SFProDisplay-Regular": require("./assets/fonts/SFProDisplay-Regular.ttf"),
    "SFProDisplay-Semibold": require("./assets/fonts/SFProDisplay-Semibold.ttf"),
    "SFProDisplay-Thin": require("./assets/fonts/SFProDisplay-Thin.ttf"),
    "SFProDisplay-Ultralight": require("./assets/fonts/SFProDisplay-Ultralight.ttf"),
    "SFProText-Bold": require("./assets/fonts/SFProText-Bold.ttf"),
    "SFProText-Heavy": require("./assets/fonts/SFProText-Heavy.ttf"),
    "SFProText-Light": require("./assets/fonts/SFProText-Light.ttf"),
    "SFProText-Medium": require("./assets/fonts/SFProText-Medium.ttf"),
    "SFProText-Regular": require("./assets/fonts/SFProText-Regular.ttf"),
    "SFProText-Semibold": require("./assets/fonts/SFProText-Semibold.ttf"),
    "ShortStack-Regular": require("./assets/fonts/ShortStack-Regular.ttf"),
    "Shrikhand-Regular": require("./assets/fonts/Shrikhand-Regular.ttf"),
    "SigmarOne-Regular": require("./assets/fonts/SigmarOne-Regular.ttf"),
    "Sillii Willinn Font": require("./assets/fonts/Sillii Willinn Font.ttf"),
    "SIMPLICITY PERSONALUSE": require("./assets/fonts/SIMPLICITY PERSONALUSE.ttf"),
    "SIMPLICITY SHADOW PERSONAL USE": require("./assets/fonts/SIMPLICITY SHADOW PERSONAL USE.ttf"),
    Simplicity: require("./assets/fonts/Simplicity.ttf"),
    Sin_City: require("./assets/fonts/Sin_City.ttf"),
    sing_14l: require("./assets/fonts/sing_14l.ttf"),
    "Slackey-Regular": require("./assets/fonts/Slackey-Regular.ttf"),
    soloist1: require("./assets/fonts/soloist1.ttf"),
    soloist3d: require("./assets/fonts/soloist3d.ttf"),
    soloistacad: require("./assets/fonts/soloistacad.ttf"),
    soloistchrome: require("./assets/fonts/soloistchrome.ttf"),
    soloistcond1: require("./assets/fonts/soloistcond1.ttf"),
    soloistexpand1: require("./assets/fonts/soloistexpand1.ttf"),
    soloistextraital1: require("./assets/fonts/soloistextraital1.ttf"),
    soloistgrad1: require("./assets/fonts/soloistgrad1.ttf"),
    soloisthalf1: require("./assets/fonts/soloisthalf1.ttf"),
    soloisthalf21: require("./assets/fonts/soloisthalf21.ttf"),
    soloisthalf: require("./assets/fonts/soloisthalf.ttf"),
    soloistital1: require("./assets/fonts/soloistital1.ttf"),
    soloistlaser1: require("./assets/fonts/soloistlaser1.ttf"),
    soloistlaserital1: require("./assets/fonts/soloistlaserital1.ttf"),
    soloistleft1: require("./assets/fonts/soloistleft1.ttf"),
    soloistout: require("./assets/fonts/soloistout.ttf"),
    soloiststraight1: require("./assets/fonts/soloiststraight1.ttf"),
    soloisttitle1: require("./assets/fonts/soloisttitle1.ttf"),
    soupofjustice: require("./assets/fonts/soupofjustice.ttf"),
    speedwagon3dital: require("./assets/fonts/speedwagon3dital.ttf"),
    speedwagon3d: require("./assets/fonts/speedwagon3d.ttf"),
    speedwagoncondital: require("./assets/fonts/speedwagoncondital.ttf"),
    speedwagoncond: require("./assets/fonts/speedwagoncond.ttf"),
    speedwagonexpandital: require("./assets/fonts/speedwagonexpandital.ttf"),
    speedwagonexpand: require("./assets/fonts/speedwagonexpand.ttf"),
    speedwagonhalfital: require("./assets/fonts/speedwagonhalfital.ttf"),
    speedwagonhalf: require("./assets/fonts/speedwagonhalf.ttf"),
    speedwagonital: require("./assets/fonts/speedwagonital.ttf"),
    speedwagonlaserital: require("./assets/fonts/speedwagonlaserital.ttf"),
    speedwagonlaser: require("./assets/fonts/speedwagonlaser.ttf"),
    speedwagonleft: require("./assets/fonts/speedwagonleft.ttf"),
    speedwagonsuperital: require("./assets/fonts/speedwagonsuperital.ttf"),
    speedwagon: require("./assets/fonts/speedwagon.ttf"),
    speedwagonxtraexpandital: require("./assets/fonts/speedwagonxtraexpandital.ttf"),
    speedwagonxtraexpand: require("./assets/fonts/speedwagonxtraexpand.ttf"),
    "SpicyRice-Regular": require("./assets/fonts/SpicyRice-Regular.ttf"),
    Splatch: require("./assets/fonts/Splatch.ttf"),
    Squirk: require("./assets/fonts/Squirk.otf"),
    "Star Wars": require("./assets/fonts/Star Wars.ttf"),
    Starborn: require("./assets/fonts/Starborn.ttf"),
    "Stella Demo": require("./assets/fonts/Stella Demo.ttf"),
    strude: require("./assets/fonts/strude.ttf"),
    SugarpunchDEMO: require("./assets/fonts/SugarpunchDEMO.otf"),
    "Summer Splash Display": require("./assets/fonts/Summer Splash Display.otf"),
    "Summer Splash": require("./assets/fonts/Summer Splash.otf"),
    "Sunkist Squash": require("./assets/fonts/Sunkist Squash.ttf"),
    "Super Comic": require("./assets/fonts/Super Comic.otf"),
    //"Super Mario.TTF": require("./assets/fonts/Super Mario.TTF"),
    "Supercell-magic-webfont": require("./assets/fonts/Supercell-magic-webfont.ttf"),
    "sweet purple": require("./assets/fonts/sweet purple.ttf"),
    "Teko-Bold": require("./assets/fonts/Teko-Bold.ttf"),
    "Teko-Light": require("./assets/fonts/Teko-Light.ttf"),
    "Teko-Medium": require("./assets/fonts/Teko-Medium.ttf"),
    "Teko-Regular": require("./assets/fonts/Teko-Regular.ttf"),
    "Teko-SemiBold": require("./assets/fonts/Teko-SemiBold.ttf"),
    "The Blacklist": require("./assets/fonts/The Blacklist.ttf"),
    "TitanOne-Regular": require("./assets/fonts/TitanOne-Regular.ttf"),
    Toxico: require("./assets/fonts/Toxico.otf"),
    "TradeWinds-Regular": require("./assets/fonts/TradeWinds-Regular.ttf"),
    //"TT0206C_.TTF": require("./assets/fonts/TT0206C_.TTF"),
    "Unicorn Pop": require("./assets/fonts/Unicorn Pop.ttf"),
    usuzi3dital: require("./assets/fonts/usuzi3dital.ttf"),
    usuzi3d: require("./assets/fonts/usuzi3d.ttf"),
    usuziboldital: require("./assets/fonts/usuziboldital.ttf"),
    usuzibold: require("./assets/fonts/usuzibold.ttf"),
    usuzicondital: require("./assets/fonts/usuzicondital.ttf"),
    usuzicond: require("./assets/fonts/usuzicond.ttf"),
    usuziexpandital: require("./assets/fonts/usuziexpandital.ttf"),
    usuziexpand: require("./assets/fonts/usuziexpand.ttf"),
    usuzigradital: require("./assets/fonts/usuzigradital.ttf"),
    usuzigrad: require("./assets/fonts/usuzigrad.ttf"),
    usuzihalfital: require("./assets/fonts/usuzihalfital.ttf"),
    usuzihalf: require("./assets/fonts/usuzihalf.ttf"),
    usuziital: require("./assets/fonts/usuziital.ttf"),
    usuzileft: require("./assets/fonts/usuzileft.ttf"),
    usuzisemital: require("./assets/fonts/usuzisemital.ttf"),
    usuzi: require("./assets/fonts/usuzi.ttf"),
    "VTC- GarageSaleOutlined": require("./assets/fonts/VTC- GarageSaleOutlined.ttf"),
    "VTC-GarageSale": require("./assets/fonts/VTC-GarageSale.ttf"),
    "VTC-GarageSaleOutlined": require("./assets/fonts/VTC-GarageSaleOutlined.otf"),
    "WalterTurncoat-Regular": require("./assets/fonts/WalterTurncoat-Regular.ttf"),
    "WendyOne-Regular": require("./assets/fonts/WendyOne-Regular.ttf"),
    "White On Black": require("./assets/fonts/White On Black.ttf"),
    "Wicked Mouse Demo": require("./assets/fonts/Wicked Mouse Demo.otf"),
    "ZCOOLKuaiLe-Regular": require("./assets/fonts/ZCOOLKuaiLe-Regular.ttf"),
  });

  const onLayoutRootView = useCallback(async () => {
    if (fontsLoaded || fontError) {
      await SplashScreen.hideAsync();
    }
  }, [fontsLoaded, fontError]);

  if (!fontsLoaded && !fontError) {
    return null;
  }

  return (
    <View style={{ flex: 1 }} onLayout={onLayoutRootView}>
      <Provider store={store}>
        <NavigationProvider />
        <StatusBar style="auto" />
      </Provider>
    </View>
  );
}
